/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: v0.1.0-next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateDeviceRequest {
    /// The public key in PEM format
    #[serde(rename = "public_key_pem")]
    pub public_key_pem: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The version of the agent the device is running
    #[serde(rename = "agent_version", skip_serializing_if = "Option::is_none")]
    pub agent_version: Option<String>,
}

impl ActivateDeviceRequest {
    pub fn new(public_key_pem: String) -> ActivateDeviceRequest {
        ActivateDeviceRequest {
            public_key_pem,
            name: None,
            agent_version: None,
        }
    }
}

