/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiGitCommit {
    #[serde(rename = "906c0503b2ff19a7c018288356f89b2881374061")]
    API_GIT_COMMIT,

}

impl std::fmt::Display for ApiGitCommit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::API_GIT_COMMIT => write!(f, "906c0503b2ff19a7c018288356f89b2881374061"),
        }
    }
}

impl Default for ApiGitCommit {
    fn default() -> ApiGitCommit {
        Self::API_GIT_COMMIT
    }
}

