/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: v0.1.0-next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseRelease {
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the release.
    #[serde(rename = "id")]
    pub id: String,
    /// The version of the release.
    #[serde(rename = "version")]
    pub version: String,
    /// Timestamp of when the release was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the release was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl BaseRelease {
    pub fn new(object: Object, id: String, version: String, created_at: String, updated_at: String) -> BaseRelease {
        BaseRelease {
            object,
            id,
            version,
            created_at,
            updated_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "release")]
    Release,
}

impl Default for Object {
    fn default() -> Object {
        Self::Release
    }
}

