/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseDeployment {
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the deployment.
    #[serde(rename = "id")]
    pub id: String,
    /// The description of the deployment.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "status")]
    pub status: models::DeploymentStatus,
    #[serde(rename = "activity_status")]
    pub activity_status: models::DeploymentActivityStatus,
    #[serde(rename = "error_status")]
    pub error_status: models::DeploymentErrorStatus,
    #[serde(rename = "target_status")]
    pub target_status: models::DeploymentTargetStatus,
    /// ID of the device.
    #[serde(rename = "device_id")]
    pub device_id: String,
    /// The version of the release.
    #[serde(rename = "release_id")]
    pub release_id: String,
    /// Timestamp of when the device release was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the device release was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl BaseDeployment {
    pub fn new(
        object: Object,
        id: String,
        description: String,
        status: models::DeploymentStatus,
        activity_status: models::DeploymentActivityStatus,
        error_status: models::DeploymentErrorStatus,
        target_status: models::DeploymentTargetStatus,
        device_id: String,
        release_id: String,
        created_at: String,
        updated_at: String,
    ) -> BaseDeployment {
        BaseDeployment {
            object,
            id,
            description,
            status,
            activity_status,
            error_status,
            target_status,
            device_id,
            release_id,
            created_at,
            updated_at,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "deployment")]
    Deployment,
}

impl Default for Object {
    fn default() -> Object {
        Self::Deployment
    }
}
