/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseGitCommit {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sha")]
    pub sha: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "repository_owner")]
    pub repository_owner: String,
    #[serde(rename = "repository_name")]
    pub repository_name: String,
    #[serde(rename = "repository_type")]
    pub repository_type: models::GitRepositoryType,
    #[serde(rename = "repository_url")]
    pub repository_url: String,
    #[serde(rename = "commit_url")]
    pub commit_url: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl BaseGitCommit {
    pub fn new(object: Object, id: String, sha: String, message: String, repository_owner: String, repository_name: String, repository_type: models::GitRepositoryType, repository_url: String, commit_url: String, created_at: String) -> BaseGitCommit {
        BaseGitCommit {
            object,
            id,
            sha,
            message,
            repository_owner,
            repository_name,
            repository_type,
            repository_url,
            commit_url,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "git_commit")]
    GitCommit,
}

impl Default for Object {
    fn default() -> Object {
        Self::GitCommit
    }
}

