/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentErrorStatus : Last known error state of the deployment. - None: no errors - Retrying: an error has been encountered and the agent is retrying to reach the target status - Failed: a fatal error has been encountered; the deployment is archived and (if deployed) removed from the device
/// Last known error state of the deployment. - None: no errors - Retrying: an error has been encountered and the agent is retrying to reach the target status - Failed: a fatal error has been encountered; the deployment is archived and (if deployed) removed from the device
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentErrorStatus {
    #[serde(rename = "none")]
    DEPLOYMENT_ERROR_STATUS_NONE,
    #[serde(rename = "failed")]
    DEPLOYMENT_ERROR_STATUS_FAILED,
    #[serde(rename = "retrying")]
    DEPLOYMENT_ERROR_STATUS_RETRYING,
}

impl std::fmt::Display for DeploymentErrorStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_ERROR_STATUS_NONE => write!(f, "none"),
            Self::DEPLOYMENT_ERROR_STATUS_FAILED => write!(f, "failed"),
            Self::DEPLOYMENT_ERROR_STATUS_RETRYING => write!(f, "retrying"),
        }
    }
}

impl Default for DeploymentErrorStatus {
    fn default() -> DeploymentErrorStatus {
        Self::DEPLOYMENT_ERROR_STATUS_NONE
    }
}
