/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentListExpansion {
    #[serde(rename = "total_count")]
    DEPLOYMENT_LIST_EXPAND_TOTAL_COUNT,
    #[serde(rename = "release")]
    DEPLOYMENT_LIST_EXPAND_RELEASE,
    #[serde(rename = "config_instances")]
    DEPLOYMENT_LIST_EXPAND_CONFIG_INSTANCES,
}

impl std::fmt::Display for DeploymentListExpansion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_LIST_EXPAND_TOTAL_COUNT => write!(f, "total_count"),
            Self::DEPLOYMENT_LIST_EXPAND_RELEASE => write!(f, "release"),
            Self::DEPLOYMENT_LIST_EXPAND_CONFIG_INSTANCES => write!(f, "config_instances"),
        }
    }
}

impl Default for DeploymentListExpansion {
    fn default() -> DeploymentListExpansion {
        Self::DEPLOYMENT_LIST_EXPAND_TOTAL_COUNT
    }
}
