/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: v0.1.0-next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentExpansion {
    #[serde(rename = "release")]
    DEPLOYMENT_EXPAND_RELEASE,
    #[serde(rename = "config_instances")]
    DEPLOYMENT_EXPAND_CONFIG_INSTANCES,

}

impl std::fmt::Display for DeploymentExpansion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_EXPAND_RELEASE => write!(f, "release"),
            Self::DEPLOYMENT_EXPAND_CONFIG_INSTANCES => write!(f, "config_instances"),
        }
    }
}

impl Default for DeploymentExpansion {
    fn default() -> DeploymentExpansion {
        Self::DEPLOYMENT_EXPAND_RELEASE
    }
}

