/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: v0.1.0-next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Device {
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the device.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the device.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: models::DeviceStatus,
    /// Timestamp of when the device was last made an initial connection (this is not the same as the last time the device was seen).
    #[serde(rename = "last_connected_at", deserialize_with = "Option::deserialize")]
    pub last_connected_at: Option<String>,
    /// Timestamp of when the device was last disconnected (this is not the same as the last time the device was seen).
    #[serde(rename = "last_disconnected_at", deserialize_with = "Option::deserialize")]
    pub last_disconnected_at: Option<String>,
    /// Timestamp of when the device was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the device was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Device {
    pub fn new(object: Object, id: String, name: String, status: models::DeviceStatus, last_connected_at: Option<String>, last_disconnected_at: Option<String>, created_at: String, updated_at: String) -> Device {
        Device {
            object,
            id,
            name,
            status,
            last_connected_at,
            last_disconnected_at,
            created_at,
            updated_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "device")]
    Device,
}

impl Default for Object {
    fn default() -> Object {
        Self::Device
    }
}

