/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceStatus : The status of the device. - Inactive: The miru agent has not yet been installed / authenticated - Activating: The miru agent is currently being installed / authenticated (should only last for a few seconds) - Online: The miru agent has successfully pinged the server within the last 60 seconds. - Offline: The miru agent has not successfully pinged the server within the last 60 seconds (e.g. network issues, device is powered off, etc.)
/// The status of the device. - Inactive: The miru agent has not yet been installed / authenticated - Activating: The miru agent is currently being installed / authenticated (should only last for a few seconds) - Online: The miru agent has successfully pinged the server within the last 60 seconds. - Offline: The miru agent has not successfully pinged the server within the last 60 seconds (e.g. network issues, device is powered off, etc.)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceStatus {
    #[serde(rename = "inactive")]
    DEVICE_STATUS_INACTIVE,
    #[serde(rename = "activating")]
    DEVICE_STATUS_ACTIVATING,
    #[serde(rename = "online")]
    DEVICE_STATUS_ONLINE,
    #[serde(rename = "offline")]
    DEVICE_STATUS_OFFLINE,
}

impl std::fmt::Display for DeviceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEVICE_STATUS_INACTIVE => write!(f, "inactive"),
            Self::DEVICE_STATUS_ACTIVATING => write!(f, "activating"),
            Self::DEVICE_STATUS_ONLINE => write!(f, "online"),
            Self::DEVICE_STATUS_OFFLINE => write!(f, "offline"),
        }
    }
}

impl Default for DeviceStatus {
    fn default() -> DeviceStatus {
        Self::DEVICE_STATUS_INACTIVE
    }
}
