/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: v0.1.0-next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "params")]
    pub params: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "debug_message")]
    pub debug_message: String,
}

impl Error {
    pub fn new(code: String, params: std::collections::HashMap<String, serde_json::Value>, message: String, debug_message: String) -> Error {
        Error {
            code,
            params,
            message,
            debug_message,
        }
    }
}

