/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedList {
    #[serde(rename = "object")]
    pub object: Object,
    /// The total number of items in the list. By default the total count is not returned. The total count must be expanded (using expand=total_count) to get the total number of items in the list.
    #[serde(rename = "total_count")]
    pub total_count: i64,
    /// The maximum number of items to return. A limit of 15 with an offset of 0 returns items 1-15.
    #[serde(rename = "limit")]
    pub limit: i32,
    /// The offset of the items to return. An offset of 10 with a limit of 10 returns items 11-20.
    #[serde(rename = "offset")]
    pub offset: i32,
    /// True if there are more items in the list to return. False if there are no more items to return.
    #[serde(rename = "has_more")]
    pub has_more: bool,
}

impl PaginatedList {
    pub fn new(
        object: Object,
        total_count: i64,
        limit: i32,
        offset: i32,
        has_more: bool,
    ) -> PaginatedList {
        PaginatedList {
            object,
            total_count,
            limit,
            offset,
            has_more,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "list")]
    List,
}

impl Default for Object {
    fn default() -> Object {
        Self::List
    }
}
