/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ping {
    /// The unique identifier of the ping message.
    #[serde(rename = "message_id")]
    pub message_id: String,
    /// The timestamp of when the ping was sent.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl Ping {
    pub fn new(message_id: String, timestamp: String) -> Ping {
        Ping {
            message_id,
            timestamp,
        }
    }
}

