/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: v0.1.0-next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pong {
    #[serde(rename = "message_id")]
    pub message_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl Pong {
    pub fn new(message_id: String, timestamp: String) -> Pong {
        Pong {
            message_id,
            timestamp,
        }
    }
}

