/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: v0.1.0-next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncDevice {
    #[serde(rename = "is_synced")]
    pub is_synced: bool,
}

impl SyncDevice {
    pub fn new(is_synced: bool) -> SyncDevice {
        SyncDevice {
            is_synced,
        }
    }
}

