/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenResponse {
    /// The token.
    #[serde(rename = "token")]
    pub token: String,
    /// The expiration date and time of the token.
    #[serde(rename = "expires_at")]
    pub expires_at: String,
}

impl TokenResponse {
    pub fn new(token: String, expires_at: String) -> TokenResponse {
        TokenResponse { token, expires_at }
    }
}
