/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: v0.1.0-next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDeploymentRequest {
    #[serde(rename = "activity_status", skip_serializing_if = "Option::is_none")]
    pub activity_status: Option<models::DeploymentActivityStatus>,
    #[serde(rename = "error_status", skip_serializing_if = "Option::is_none")]
    pub error_status: Option<models::DeploymentErrorStatus>,
}

impl UpdateDeploymentRequest {
    pub fn new() -> UpdateDeploymentRequest {
        UpdateDeploymentRequest {
            activity_status: None,
            error_status: None,
        }
    }
}

