/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDeploymentRequest {
    #[serde(rename = "activity_status", skip_serializing_if = "Option::is_none")]
    pub activity_status: Option<models::DeploymentActivityStatus>,
    #[serde(rename = "error_status", skip_serializing_if = "Option::is_none")]
    pub error_status: Option<models::DeploymentErrorStatus>,
    /// Timestamp of when the deployment was deployed. Set by the agent.
    #[serde(rename = "deployed_at", skip_serializing_if = "Option::is_none")]
    pub deployed_at: Option<String>,
    /// Timestamp of when the deployment was archived. Set by the agent.
    #[serde(rename = "archived_at", skip_serializing_if = "Option::is_none")]
    pub archived_at: Option<String>,
}

impl UpdateDeploymentRequest {
    pub fn new() -> UpdateDeploymentRequest {
        UpdateDeploymentRequest {
            activity_status: None,
            error_status: None,
            deployed_at: None,
            archived_at: None,
        }
    }
}

