/*
 * Miru Backend-Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Version {
    /// The version of the application.
    #[serde(rename = "version")]
    pub version: String,
    /// The git commit of the application.
    #[serde(rename = "git_commit")]
    pub git_commit: String,
    /// The API version of the application.
    #[serde(rename = "api_version")]
    pub api_version: String,
    /// The git commit of the API.
    #[serde(rename = "api_git_commit")]
    pub api_git_commit: String,
    /// The version of Go.
    #[serde(rename = "go_version")]
    pub go_version: String,
    /// The build date of the application.
    #[serde(rename = "build_date")]
    pub build_date: String,
    /// The operating system of the application.
    #[serde(rename = "os")]
    pub os: String,
    /// The architecture of the application.
    #[serde(rename = "arch")]
    pub arch: String,
}

impl Version {
    pub fn new(
        version: String,
        git_commit: String,
        api_version: String,
        api_git_commit: String,
        go_version: String,
        build_date: String,
        os: String,
        arch: String,
    ) -> Version {
        Version {
            version,
            git_commit,
            api_version,
            api_git_commit,
            go_version,
            build_date,
            os,
            arch,
        }
    }
}
