openapi: 3.0.3
info:
  title: Miru Agent API
  description: The API between the Miru Agent and any external client living on the same device as the Miru Agent
  version: 0.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost/{version}
    description: localhost
    variables:
      version:
        default: beta
        enum:
          - beta
paths:
  /health:
    get:
      tags:
        - Agent
      summary: Health
      description: Retrieve the health of the agent.
      responses:
        '200':
          description: Successfully retrieved the health of the agent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /version:
    get:
      tags:
        - Agent
      summary: Version
      description: Retrieve the version of the agent.
      responses:
        '200':
          description: Successfully retrieved the version of the agent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
  /deployments/{deployment_id}:
    get:
      tags:
        - Deployments
      summary: Get a deployment by ID
      operationId: getDeployment
      parameters:
        - $ref: '#/components/parameters/deployment_id'
      responses:
        '200':
          description: Successfully retrieved the deployment.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
  /deployments:
    post:
      tags:
        - Deployments
      summary: Create a deployment
      operationId: createDeployment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDeploymentRequest'
      responses:
        '200':
          description: Successfully created the deployment.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
  /deployments/current:
    get:
      tags:
        - Deployments
      summary: Get the current deployment
      operationId: getCurrentDeployment
      responses:
        '200':
          description: Successfully retrieved the current deployment.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
  /device:
    get:
      tags:
        - Devices
      summary: Get
      description: Retrieve the device.
      operationId: getDevice
      responses:
        '200':
          description: Successfully retrieved the device.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
  /device/sync:
    post:
      tags:
        - Devices
      summary: Sync
      description: Manually force a device sync with the edits made in the dashboard.
      operationId: syncDevice
      responses:
        '200':
          description: Successfully synced the device.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncDeviceResponse'
  /releases/current:
    get:
      tags:
        - Releases
      summary: Get the current release
      description: Retrieve the current release.
      operationId: getCurrentRelease
      responses:
        '200':
          description: Successfully retrieved the current release.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          description: The status of the agent.
          example: ok
    VersionResponse:
      type: object
      required:
        - version
        - commit
      properties:
        version:
          type: string
          description: The version of the agent.
          example: v1.0.0
        commit:
          type: string
          description: The commit hash of the agent.
          example: a1b2c3d4
    DeploymentStatus:
      type: string
      description: |
        This status merges the 'activity_status' and 'error_status' fields, with error states taking precedence over activity states when errors are present. For example, if the activity status is 'deployed' but the error status is 'failed', the status is 'failed'. However, if the error status is 'none' and the activity status is 'deployed', the status is 'deployed'.
      enum:
        - drifted
        - staged
        - queued
        - deployed
        - archived
        - failed
        - retrying
      x-enum-varnames:
        - DEPLOYMENT_STATUS_DRIFTED
        - DEPLOYMENT_STATUS_STAGED
        - DEPLOYMENT_STATUS_QUEUED
        - DEPLOYMENT_STATUS_DEPLOYED
        - DEPLOYMENT_STATUS_ARCHIVED
        - DEPLOYMENT_STATUS_FAILED
        - DEPLOYMENT_STATUS_RETRYING
    DeploymentActivityStatus:
      type: string
      description: |
        Last known activity state of the deployment.
        - Drifted: device's configurations have drifted since this deployment was staged, and the deployment needs to be reviewed before it can be deployed
        - Staged: is ready to be deployed
        - Queued: the deployment's config instances are waiting to be received by the device; will be deployed as soon as the device is online
        - Deployed: the deployment's config instances are currently available for consumption on the device
        - Archived: the deployment is available for historical reference but cannot be deployed and is not active on the device
      enum:
        - drifted
        - staged
        - queued
        - deployed
        - archived
      x-enum-varnames:
        - DEPLOYMENT_ACTIVITY_STATUS_DRIFTED
        - DEPLOYMENT_ACTIVITY_STATUS_STAGED
        - DEPLOYMENT_ACTIVITY_STATUS_QUEUED
        - DEPLOYMENT_ACTIVITY_STATUS_DEPLOYED
        - DEPLOYMENT_ACTIVITY_STATUS_ARCHIVED
    DeploymentErrorStatus:
      type: string
      description: |
        Last known error state of the deployment.
        - None: no errors
        - Retrying: an error has been encountered and the agent is retrying to reach the target status
        - Failed: a fatal error has been encountered; the deployment is archived and (if deployed) removed from the device
      enum:
        - none
        - failed
        - retrying
      x-enum-varnames:
        - DEPLOYMENT_ERROR_STATUS_NONE
        - DEPLOYMENT_ERROR_STATUS_FAILED
        - DEPLOYMENT_ERROR_STATUS_RETRYING
    DeploymentTargetStatus:
      type: string
      description: |
        Desired state of the deployment.
        - Staged: is ready to be deployed
        - Deployed: all config instances part of the deployment are available for consumption on the device
        - Archived: the deployment is available for historical reference but cannot be deployed and is not active on the device
      enum:
        - staged
        - deployed
        - archived
      x-enum-varnames:
        - DEPLOYMENT_TARGET_STATUS_STAGED
        - DEPLOYMENT_TARGET_STATUS_DEPLOYED
        - DEPLOYMENT_TARGET_STATUS_ARCHIVED
    BaseDeployment:
      title: Base Deployment
      type: object
      required:
        - object
        - id
        - description
        - status
        - activity_status
        - error_status
        - target_status
        - device_id
        - release_id
        - created_at
        - updated_at
      properties:
        object:
          type: string
          enum:
            - deployment
          example: deployment
          x-stainless-const: true
        id:
          type: string
          example: dpl_123
          description: ID of the deployment.
        description:
          type: string
          example: Deployment for the motion control config instance
          description: The description of the deployment.
        status:
          $ref: '#/components/schemas/DeploymentStatus'
        activity_status:
          $ref: '#/components/schemas/DeploymentActivityStatus'
        error_status:
          $ref: '#/components/schemas/DeploymentErrorStatus'
        target_status:
          $ref: '#/components/schemas/DeploymentTargetStatus'
        device_id:
          type: string
          example: dvc_123
          description: ID of the device.
        release_id:
          type: string
          example: v1.0.0
          description: The version of the release.
        created_at:
          type: string
          format: date-time
          example: '2024-01-01T00:00:00Z'
          description: Timestamp of when the device release was created.
        updated_at:
          type: string
          format: date-time
          example: '2024-01-01T00:00:00Z'
          description: Timestamp of when the device release was last updated.
    BaseConfigInstance:
      title: Base Config Instance
      type: object
      required:
        - object
        - id
        - config_type_name
        - filepath
        - created_at
        - config_schema_id
        - config_type_id
      properties:
        object:
          type: string
          enum:
            - config_instance
          example: config_instance
          x-stainless-const: true
        id:
          type: string
          example: cfg_inst_123
          description: ID of the config instance.
        config_type_name:
          type: string
          example: Motion Control
          description: The name of the config type.
        filepath:
          type: string
          example: /v1/motion-control.json
          description: The file path to deploy the config instance relative to `/srv/miru/config_instances`. `v1/motion-control.json` would deploy to `/srv/miru/config_instances/v1/motion-control.json`.
        created_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: The timestamp of when the config instance was created.
        config_schema_id:
          type: string
          example: cfg_sch_123
          description: ID of the config schema which the config instance must adhere to.
        config_type_id:
          type: string
          example: cfg_type_123
          description: ID of the config type which the config instance (and its schema) is a part of.
    InstanceFormat:
      title: Instance Format
      type: string
      enum:
        - json
      x-enum-varnames:
        - INSTANCE_FORMAT_JSON
    InstanceContent:
      title: Instance Content
      type: object
      required:
        - format
        - data
      properties:
        format:
          $ref: '#/components/schemas/InstanceFormat'
        data:
          type: string
          description: The configuration values associated with the config instance.
          example: |
            {
              "enable_autonomy": true,
              "enable_remote_control": true,
              "max_payload_kg": 10.0
            }
    ConfigInstance:
      allOf:
        - $ref: '#/components/schemas/BaseConfigInstance'
        - type: object
          required:
            - content
          properties:
            content:
              allOf:
                - $ref: '#/components/schemas/InstanceContent'
              description: The configuration values associated with the config instance
    Deployment:
      allOf:
        - $ref: '#/components/schemas/BaseDeployment'
        - type: object
          properties:
            config_instances:
              type: array
              items:
                $ref: '#/components/schemas/ConfigInstance'
              example: null
    CreateDeploymentRequest:
      title: Create Deployment Request
      type: object
      required:
        - description
        - parent_id
        - config_instance_ids
      properties:
        description:
          type: string
          description: The description of the deployment.
          example: Deployment for the motion control config instance
        parent_id:
          type: string
          description: The ID of the deployment that was deployment before this one.
          example: dpl_123
        config_instance_ids:
          type: array
          description: The IDs of the config instances to deploy. A deployment must have exactly one config instance for each config schema in the deployment's release.
          items:
            type: string
            example: cfg_inst_123
    DeviceStatus:
      type: string
      description: |
        The status of the device.
        - Online: The miru agent is connected
        - Offline: The miru agent is disconnected (e.g. network issues, device is powered off, etc.)
      enum:
        - online
        - offline
      x-enum-varnames:
        - DEVICE_STATUS_ONLINE
        - DEVICE_STATUS_OFFLINE
    Device:
      title: Device
      type: object
      required:
        - object
        - id
        - name
        - status
        - last_synced_at
        - last_connected_at
        - last_disconnected_at
      properties:
        object:
          type: string
          enum:
            - device
          example: device
          x-stainless-const: true
        id:
          type: string
          example: dvc_123
          description: ID of the device.
        name:
          type: string
          example: My Device
          description: Name of the device.
        status:
          $ref: '#/components/schemas/DeviceStatus'
        last_synced_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: Timestamp of when the device was last synced.
        last_connected_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: Timestamp of the last successful connection event with the backend.
        last_disconnected_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: Timestamp of the last successful disconnection event with the backend.
    SyncDeviceResult:
      type: string
      description: The result of attempting to sync the device.
      enum:
        - success
        - network_connection_error
        - in_cooldown
      x-enum-varnames:
        - SYNC_DEVICE_RESULT_SUCCESS
        - SYNC_DEVICE_RESULT_NETWORK_CONNECTION_ERROR
        - SYNC_DEVICE_RESULT_IN_COOLDOWN
    SyncDeviceResponse:
      title: Sync Device Response
      type: object
      required:
        - code
        - message
        - last_synced_at
        - last_attempted_sync_at
        - in_cooldown
        - cooldown_ends_at
      properties:
        code:
          $ref: '#/components/schemas/SyncDeviceResult'
        message:
          type: string
          example: Device is not connected to the backend.
          description: The message of the result.
        last_synced_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: Timestamp of when the device was last synced.
        last_attempted_sync_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: Timestamp of when the last *attempted* sync occurred.
        in_cooldown:
          type: boolean
          example: true
          description: Whether the device is currently in cooldown.
        cooldown_ends_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: Timestamp of when the cooldown will end.
    BaseRelease:
      title: Base Release
      type: object
      required:
        - object
        - id
        - version
        - created_at
        - updated_at
      properties:
        object:
          type: string
          enum:
            - release
          example: release
          x-stainless-const: true
        id:
          type: string
          example: rls_123
          description: ID of the release.
        version:
          type: string
          example: v1.0.0
          description: The version of the release.
        created_at:
          type: string
          format: date-time
          example: '2024-01-01T00:00:00Z'
          description: Timestamp of when the release was created.
        updated_at:
          type: string
          format: date-time
          example: '2024-01-01T00:00:00Z'
          description: Timestamp of when the release was last updated.
    Release:
      allOf:
        - $ref: '#/components/schemas/BaseRelease'
    Error:
      type: object
      required:
        - code
        - params
        - message
      properties:
        code:
          type: string
          example: invalid_request
        params:
          type: object
          additionalProperties: true
          example:
            param1: value1
            param2: value2
        message:
          type: string
          example: This is a message for a user
  parameters:
    deployment_id:
      name: deployment_id
      in: path
      required: true
      description: The unique identifier of the deployment.
      schema:
        type: string
        example: dpl_123
