[package]
name = "miru-agent"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
include = ["src/**/*"]
build = "build.rs"

[features]
test = []

[lints.clippy]
new_without_default = "allow"

[dependencies]
atomicwrites = { workspace = true }
aws-sdk-s3 = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
google-cloud-storage = { workspace = true }
google-cloud-auth = { workspace = true }
google-cloud-gax = { workspace = true }
http = { workspace = true }
nix = { workspace = true }
backend-api = { workspace = true }
device-api = { workspace = true }
openssl = { workspace = true }
reqwest = { workspace = true }
rumqttc = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sysinfo = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }

[dev-dependencies]
aws-sdk-s3 = { workspace = true }
aws-smithy-http-client = { workspace = true, features = ["test-util"] }
aws-smithy-types = { workspace = true }
google-cloud-gax = { workspace = true }
google-cloud-iam-v1 = "1.10"
google-cloud-longrunning = "1.11"
google-cloud-storage = { workspace = true }
http = { workspace = true }
http-body-util = "0.1"
mockall = "0.14"
pastey = "0.2"
reqwest = { workspace = true, features = ["json"] }
rumqttd = { workspace = true }
serial_test = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
