/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiGitCommit {
    #[serde(rename = "dirty-efdbdd66d318e9be84838e866838f15e9e0fe6c7")]
    API_GIT_COMMIT,

}

impl std::fmt::Display for ApiGitCommit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::API_GIT_COMMIT => write!(f, "dirty-efdbdd66d318e9be84838e866838f15e9e0fe6c7"),
        }
    }
}

impl Default for ApiGitCommit {
    fn default() -> ApiGitCommit {
        Self::API_GIT_COMMIT
    }
}

