/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigInstanceErrorStatus : Last known error state of the config instance deployment. - None: there are no errors with the config instance deployment - Retrying: an error has been encountered and the agent is attempting to try again to reach the target status - Failed: a fatal error has been encountered; the config instance is archived and (if deployed) removed from the device 
/// Last known error state of the config instance deployment. - None: there are no errors with the config instance deployment - Retrying: an error has been encountered and the agent is attempting to try again to reach the target status - Failed: a fatal error has been encountered; the config instance is archived and (if deployed) removed from the device 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigInstanceErrorStatus {
    #[serde(rename = "none")]
    CONFIG_INSTANCE_ERROR_STATUS_NONE,
    #[serde(rename = "failed")]
    CONFIG_INSTANCE_ERROR_STATUS_FAILED,
    #[serde(rename = "retrying")]
    CONFIG_INSTANCE_ERROR_STATUS_RETRYING,

}

impl std::fmt::Display for ConfigInstanceErrorStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_INSTANCE_ERROR_STATUS_NONE => write!(f, "none"),
            Self::CONFIG_INSTANCE_ERROR_STATUS_FAILED => write!(f, "failed"),
            Self::CONFIG_INSTANCE_ERROR_STATUS_RETRYING => write!(f, "retrying"),
        }
    }
}

impl Default for ConfigInstanceErrorStatus {
    fn default() -> ConfigInstanceErrorStatus {
        Self::CONFIG_INSTANCE_ERROR_STATUS_NONE
    }
}

