/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigInstanceTargetStatus : Desired state of the config instance. - Created: config instance is created and can be deployed in the future - Deployed: config instance is available for consumption on the device - Removed: config instance is available for historical reference but cannot be deployed and is not active on the device 
/// Desired state of the config instance. - Created: config instance is created and can be deployed in the future - Deployed: config instance is available for consumption on the device - Removed: config instance is available for historical reference but cannot be deployed and is not active on the device 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigInstanceTargetStatus {
    #[serde(rename = "created")]
    CONFIG_INSTANCE_TARGET_STATUS_CREATED,
    #[serde(rename = "deployed")]
    CONFIG_INSTANCE_TARGET_STATUS_DEPLOYED,
    #[serde(rename = "removed")]
    CONFIG_INSTANCE_TARGET_STATUS_REMOVED,

}

impl std::fmt::Display for ConfigInstanceTargetStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_INSTANCE_TARGET_STATUS_CREATED => write!(f, "created"),
            Self::CONFIG_INSTANCE_TARGET_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::CONFIG_INSTANCE_TARGET_STATUS_REMOVED => write!(f, "removed"),
        }
    }
}

impl Default for ConfigInstanceTargetStatus {
    fn default() -> ConfigInstanceTargetStatus {
        Self::CONFIG_INSTANCE_TARGET_STATUS_CREATED
    }
}

