/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigInstance {
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the config instance.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the config type.
    #[serde(rename = "config_type_name")]
    pub config_type_name: String,
    /// The file path to deploy the config instance relative to `/srv/miru/config_instances`. `v1/motion-control.json` would deploy to `/srv/miru/config_instances/v1/motion-control.json`.
    #[serde(rename = "filepath")]
    pub filepath: String,
    /// The timestamp of when the config instance was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// ID of the config schema which the config instance must adhere to.
    #[serde(rename = "config_schema_id")]
    pub config_schema_id: String,
    /// ID of the config type which the config instance (and its schema) is a part of.
    #[serde(rename = "config_type_id")]
    pub config_type_id: String,
    /// The configuration values associated with the config instance
    #[serde(rename = "content")]
    pub content: Box<models::InstanceContent>,
}

impl ConfigInstance {
    pub fn new(object: Object, id: String, config_type_name: String, filepath: String, created_at: String, config_schema_id: String, config_type_id: String, content: models::InstanceContent) -> ConfigInstance {
        ConfigInstance {
            object,
            id,
            config_type_name,
            filepath,
            created_at,
            config_schema_id,
            config_type_id,
            content: Box::new(content),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "config_instance")]
    ConfigInstance,
}

impl Default for Object {
    fn default() -> Object {
        Self::ConfigInstance
    }
}

