/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigInstanceStatus : This status merges the 'activity_status' and 'error_status' fields, with error states taking precedence over activity states when errors are present. For example, if the activity status is 'deployed' but the error status is 'failed', the status is 'failed'. However, if the error status is 'none' and the activity status is 'deployed', the status is 'deployed'. 
/// This status merges the 'activity_status' and 'error_status' fields, with error states taking precedence over activity states when errors are present. For example, if the activity status is 'deployed' but the error status is 'failed', the status is 'failed'. However, if the error status is 'none' and the activity status is 'deployed', the status is 'deployed'. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigInstanceStatus {
    #[serde(rename = "created")]
    CONFIG_INSTANCE_STATUS_CREATED,
    #[serde(rename = "queued")]
    CONFIG_INSTANCE_STATUS_QUEUED,
    #[serde(rename = "deployed")]
    CONFIG_INSTANCE_STATUS_DEPLOYED,
    #[serde(rename = "removed")]
    CONFIG_INSTANCE_STATUS_REMOVED,
    #[serde(rename = "failed")]
    CONFIG_INSTANCE_STATUS_FAILED,
    #[serde(rename = "retrying")]
    CONFIG_INSTANCE_STATUS_RETRYING,

}

impl std::fmt::Display for ConfigInstanceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_INSTANCE_STATUS_CREATED => write!(f, "created"),
            Self::CONFIG_INSTANCE_STATUS_QUEUED => write!(f, "queued"),
            Self::CONFIG_INSTANCE_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::CONFIG_INSTANCE_STATUS_REMOVED => write!(f, "removed"),
            Self::CONFIG_INSTANCE_STATUS_FAILED => write!(f, "failed"),
            Self::CONFIG_INSTANCE_STATUS_RETRYING => write!(f, "retrying"),
        }
    }
}

impl Default for ConfigInstanceStatus {
    fn default() -> ConfigInstanceStatus {
        Self::CONFIG_INSTANCE_STATUS_CREATED
    }
}

