/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigInstanceActivityStatus : Last known activity state of the config instance. - Created: config instance has been created and can be deployed in the future - Queued: config instance is waiting to be received by the device; will be deployed as soon as the device is online - Deployed: config instance is currently available for consumption on the device - Removed: the config instance is available for historical reference but cannot be deployed and is not active on the device 
/// Last known activity state of the config instance. - Created: config instance has been created and can be deployed in the future - Queued: config instance is waiting to be received by the device; will be deployed as soon as the device is online - Deployed: config instance is currently available for consumption on the device - Removed: the config instance is available for historical reference but cannot be deployed and is not active on the device 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigInstanceActivityStatus {
    #[serde(rename = "created")]
    CONFIG_INSTANCE_ACTIVITY_STATUS_CREATED,
    #[serde(rename = "queued")]
    CONFIG_INSTANCE_ACTIVITY_STATUS_QUEUED,
    #[serde(rename = "deployed")]
    CONFIG_INSTANCE_ACTIVITY_STATUS_DEPLOYED,
    #[serde(rename = "removed")]
    CONFIG_INSTANCE_ACTIVITY_STATUS_REMOVED,

}

impl std::fmt::Display for ConfigInstanceActivityStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CONFIG_INSTANCE_ACTIVITY_STATUS_CREATED => write!(f, "created"),
            Self::CONFIG_INSTANCE_ACTIVITY_STATUS_QUEUED => write!(f, "queued"),
            Self::CONFIG_INSTANCE_ACTIVITY_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::CONFIG_INSTANCE_ACTIVITY_STATUS_REMOVED => write!(f, "removed"),
        }
    }
}

impl Default for ConfigInstanceActivityStatus {
    fn default() -> ConfigInstanceActivityStatus {
        Self::CONFIG_INSTANCE_ACTIVITY_STATUS_CREATED
    }
}

