/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDeploymentRequest {
    /// The description of the deployment.
    #[serde(rename = "description")]
    pub description: String,
    /// The ID of the deployment that was deployment before this one.
    #[serde(rename = "parent_id")]
    pub parent_id: String,
    /// The IDs of the config instances to deploy. A deployment must have exactly one config instance for each config schema in the deployment's release.
    #[serde(rename = "config_instance_ids")]
    pub config_instance_ids: Vec<String>,
}

impl CreateDeploymentRequest {
    pub fn new(description: String, parent_id: String, config_instance_ids: Vec<String>) -> CreateDeploymentRequest {
        CreateDeploymentRequest {
            description,
            parent_id,
            config_instance_ids,
        }
    }
}

