/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentTargetStatus : Desired state of the deployment. - Staged: is ready to be deployed - Deployed: all config instances part of the deployment are available for consumption on the device - Archived: the deployment is available for historical reference but cannot be deployed and is not active on the device 
/// Desired state of the deployment. - Staged: is ready to be deployed - Deployed: all config instances part of the deployment are available for consumption on the device - Archived: the deployment is available for historical reference but cannot be deployed and is not active on the device 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentTargetStatus {
    #[serde(rename = "staged")]
    DEPLOYMENT_TARGET_STATUS_STAGED,
    #[serde(rename = "deployed")]
    DEPLOYMENT_TARGET_STATUS_DEPLOYED,
    #[serde(rename = "archived")]
    DEPLOYMENT_TARGET_STATUS_ARCHIVED,

}

impl std::fmt::Display for DeploymentTargetStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_TARGET_STATUS_STAGED => write!(f, "staged"),
            Self::DEPLOYMENT_TARGET_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::DEPLOYMENT_TARGET_STATUS_ARCHIVED => write!(f, "archived"),
        }
    }
}

impl Default for DeploymentTargetStatus {
    fn default() -> DeploymentTargetStatus {
        Self::DEPLOYMENT_TARGET_STATUS_STAGED
    }
}

