/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentActivityStatus : Last known activity state of the deployment. - Drifted: device's configurations have drifted since this deployment was staged, and the deployment needs to be reviewed before it can be deployed - Staged: is ready to be deployed - Queued: the deployment's config instances are waiting to be received by the device; will be deployed as soon as the device is online - Deployed: the deployment's config instances are currently available for consumption on the device - Archived: the deployment is available for historical reference but cannot be deployed and is not active on the device
/// Last known activity state of the deployment. - Drifted: device's configurations have drifted since this deployment was staged, and the deployment needs to be reviewed before it can be deployed - Staged: is ready to be deployed - Queued: the deployment's config instances are waiting to be received by the device; will be deployed as soon as the device is online - Deployed: the deployment's config instances are currently available for consumption on the device - Archived: the deployment is available for historical reference but cannot be deployed and is not active on the device
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentActivityStatus {
    #[serde(rename = "drifted")]
    DEPLOYMENT_ACTIVITY_STATUS_DRIFTED,
    #[serde(rename = "staged")]
    DEPLOYMENT_ACTIVITY_STATUS_STAGED,
    #[serde(rename = "queued")]
    DEPLOYMENT_ACTIVITY_STATUS_QUEUED,
    #[serde(rename = "deployed")]
    DEPLOYMENT_ACTIVITY_STATUS_DEPLOYED,
    #[serde(rename = "archived")]
    DEPLOYMENT_ACTIVITY_STATUS_ARCHIVED,
}

impl std::fmt::Display for DeploymentActivityStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_ACTIVITY_STATUS_DRIFTED => write!(f, "drifted"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_STAGED => write!(f, "staged"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_QUEUED => write!(f, "queued"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_ARCHIVED => write!(f, "archived"),
        }
    }
}

impl Default for DeploymentActivityStatus {
    fn default() -> DeploymentActivityStatus {
        Self::DEPLOYMENT_ACTIVITY_STATUS_DRIFTED
    }
}
