/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentStatus : This status merges the 'activity_status' and 'error_status' fields, with error states taking precedence over activity states when errors are present. For example, if the activity status is 'deployed' but the error status is 'failed', the status is 'failed'. However, if the error status is 'none' and the activity status is 'deployed', the status is 'deployed'.
/// This status merges the 'activity_status' and 'error_status' fields, with error states taking precedence over activity states when errors are present. For example, if the activity status is 'deployed' but the error status is 'failed', the status is 'failed'. However, if the error status is 'none' and the activity status is 'deployed', the status is 'deployed'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentStatus {
    #[serde(rename = "drifted")]
    DEPLOYMENT_STATUS_DRIFTED,
    #[serde(rename = "staged")]
    DEPLOYMENT_STATUS_STAGED,
    #[serde(rename = "queued")]
    DEPLOYMENT_STATUS_QUEUED,
    #[serde(rename = "deployed")]
    DEPLOYMENT_STATUS_DEPLOYED,
    #[serde(rename = "archived")]
    DEPLOYMENT_STATUS_ARCHIVED,
    #[serde(rename = "failed")]
    DEPLOYMENT_STATUS_FAILED,
    #[serde(rename = "retrying")]
    DEPLOYMENT_STATUS_RETRYING,
}

impl std::fmt::Display for DeploymentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_STATUS_DRIFTED => write!(f, "drifted"),
            Self::DEPLOYMENT_STATUS_STAGED => write!(f, "staged"),
            Self::DEPLOYMENT_STATUS_QUEUED => write!(f, "queued"),
            Self::DEPLOYMENT_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::DEPLOYMENT_STATUS_ARCHIVED => write!(f, "archived"),
            Self::DEPLOYMENT_STATUS_FAILED => write!(f, "failed"),
            Self::DEPLOYMENT_STATUS_RETRYING => write!(f, "retrying"),
        }
    }
}

impl Default for DeploymentStatus {
    fn default() -> DeploymentStatus {
        Self::DEPLOYMENT_STATUS_DRIFTED
    }
}
