/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceStatus : The status of the device. - Online: The miru agent is connected - Offline: The miru agent is disconnected (e.g. network issues, device is powered off, etc.) 
/// The status of the device. - Online: The miru agent is connected - Offline: The miru agent is disconnected (e.g. network issues, device is powered off, etc.) 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceStatus {
    #[serde(rename = "online")]
    DEVICE_STATUS_ONLINE,
    #[serde(rename = "offline")]
    DEVICE_STATUS_OFFLINE,

}

impl std::fmt::Display for DeviceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEVICE_STATUS_ONLINE => write!(f, "online"),
            Self::DEVICE_STATUS_OFFLINE => write!(f, "offline"),
        }
    }
}

impl Default for DeviceStatus {
    fn default() -> DeviceStatus {
        Self::DEVICE_STATUS_ONLINE
    }
}

