/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "params", deserialize_with = "Option::deserialize")]
    pub params: Option<serde_json::Value>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "debug_message")]
    pub debug_message: String,
}

impl Error {
    pub fn new(code: String, params: Option<serde_json::Value>, message: String, debug_message: String) -> Error {
        Error {
            code,
            params,
            message,
            debug_message,
        }
    }
}

