/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HashSerializedConfigSchemaFormat {
    #[serde(rename = "json")]
    HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_JSON,
    #[serde(rename = "yaml")]
    HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_YAML,

}

impl std::fmt::Display for HashSerializedConfigSchemaFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_JSON => write!(f, "json"),
            Self::HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_YAML => write!(f, "yaml"),
        }
    }
}

impl Default for HashSerializedConfigSchemaFormat {
    fn default() -> HashSerializedConfigSchemaFormat {
        Self::HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_JSON
    }
}

