/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthResponse {
    /// The status of the agent.
    #[serde(rename = "status")]
    pub status: String,
}

impl HealthResponse {
    pub fn new(status: String) -> HealthResponse {
        HealthResponse {
            status,
        }
    }
}

