/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthResponse {
    /// The status of the agent.
    #[serde(rename = "status")]
    pub status: String,
}

impl HealthResponse {
    pub fn new(status: String) -> HealthResponse {
        HealthResponse { status }
    }
}
