/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstanceFormat {
    #[serde(rename = "json")]
    INSTANCE_FORMAT_JSON,

}

impl std::fmt::Display for InstanceFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::INSTANCE_FORMAT_JSON => write!(f, "json"),
        }
    }
}

impl Default for InstanceFormat {
    fn default() -> InstanceFormat {
        Self::INSTANCE_FORMAT_JSON
    }
}

