/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncDeviceResponse {
    #[serde(rename = "code")]
    pub code: models::SyncDeviceResult,
    /// The message of the result.
    #[serde(rename = "message")]
    pub message: String,
    /// Timestamp of when the device was last synced.
    #[serde(rename = "last_synced_at")]
    pub last_synced_at: String,
    /// Timestamp of when the last *attempted* sync occurred.
    #[serde(rename = "last_attempted_sync_at")]
    pub last_attempted_sync_at: String,
    /// Whether the device is currently in cooldown.
    #[serde(rename = "in_cooldown")]
    pub in_cooldown: bool,
    /// Timestamp of when the cooldown will end.
    #[serde(rename = "cooldown_ends_at")]
    pub cooldown_ends_at: String,
}

impl SyncDeviceResponse {
    pub fn new(code: models::SyncDeviceResult, message: String, last_synced_at: String, last_attempted_sync_at: String, in_cooldown: bool, cooldown_ends_at: String) -> SyncDeviceResponse {
        SyncDeviceResponse {
            code,
            message,
            last_synced_at,
            last_attempted_sync_at,
            in_cooldown,
            cooldown_ends_at,
        }
    }
}

