/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionResponse {
    /// The version of the agent.
    #[serde(rename = "version")]
    pub version: String,
    /// The commit hash of the agent.
    #[serde(rename = "commit")]
    pub commit: String,
}

impl VersionResponse {
    pub fn new(version: String, commit: String) -> VersionResponse {
        VersionResponse {
            version,
            commit,
        }
    }
}

