/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiGitCommit {
    #[serde(rename = "10dc72e22958a4851e7f6718f5b7542b0c7f62e1")]
    API_GIT_COMMIT,

}

impl std::fmt::Display for ApiGitCommit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::API_GIT_COMMIT => write!(f, "10dc72e22958a4851e7f6718f5b7542b0c7f62e1"),
        }
    }
}

impl Default for ApiGitCommit {
    fn default() -> ApiGitCommit {
        Self::API_GIT_COMMIT
    }
}

