/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiVersion {
    #[serde(rename = "v0.2")]
    API_VERSION,

}

impl std::fmt::Display for ApiVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::API_VERSION => write!(f, "v0.2"),
        }
    }
}

impl Default for ApiVersion {
    fn default() -> ApiVersion {
        Self::API_VERSION
    }
}

