/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiGitCommit {
    #[serde(rename = "4489e6beb6e5e0c893a456fb346c2cbfe178b48f")]
    API_GIT_COMMIT,

}

impl std::fmt::Display for ApiGitCommit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::API_GIT_COMMIT => write!(f, "4489e6beb6e5e0c893a456fb346c2cbfe178b48f"),
        }
    }
}

impl Default for ApiGitCommit {
    fn default() -> ApiGitCommit {
        Self::API_GIT_COMMIT
    }
}

