/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentRemovedBeta1Event : Payload for `deployment.removed.beta1` events.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentRemovedBeta1Event {
    /// ID of the deployment.
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,
    /// Activity status of the deployment after this event.
    #[serde(rename = "activity_status")]
    pub activity_status: String,
    /// Target status of the deployment after this event.
    #[serde(rename = "target_status")]
    pub target_status: String,
    /// Timestamp of when the deployment was archived.
    #[serde(rename = "archived_at", skip_serializing_if = "Option::is_none")]
    pub archived_at: Option<String>,
}

impl DeploymentRemovedBeta1Event {
    /// Payload for `deployment.removed.beta1` events.
    pub fn new(deployment_id: String, activity_status: String, target_status: String) -> DeploymentRemovedBeta1Event {
        DeploymentRemovedBeta1Event {
            deployment_id,
            activity_status,
            target_status,
            archived_at: None,
        }
    }
}

