/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentRemovedEvent : Emitted when a deployment's config instances have been removed from the device's filesystem and the deployment has been archived. Use this event to clean up resources or stop services that depended on the removed configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentRemovedEvent {
    /// ID of the deployment.
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,
    /// ID of the release associated with this deployment.
    #[serde(rename = "release_id")]
    pub release_id: String,
    #[serde(rename = "status")]
    pub status: models::DeploymentStatus,
    #[serde(rename = "activity_status")]
    pub activity_status: models::DeploymentActivityStatus,
    #[serde(rename = "error_status")]
    pub error_status: models::DeploymentErrorStatus,
    #[serde(rename = "target_status")]
    pub target_status: models::DeploymentTargetStatus,
    /// Timestamp of when the deployment was archived.
    #[serde(rename = "archived_at", skip_serializing_if = "Option::is_none")]
    pub archived_at: Option<String>,
}

impl DeploymentRemovedEvent {
    /// Emitted when a deployment's config instances have been removed from the device's filesystem and the deployment has been archived. Use this event to clean up resources or stop services that depended on the removed configuration.
    pub fn new(deployment_id: String, release_id: String, status: models::DeploymentStatus, activity_status: models::DeploymentActivityStatus, error_status: models::DeploymentErrorStatus, target_status: models::DeploymentTargetStatus) -> DeploymentRemovedEvent {
        DeploymentRemovedEvent {
            deployment_id,
            release_id,
            status,
            activity_status,
            error_status,
            target_status,
            archived_at: None,
        }
    }
}

