/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentDeployedEvent : Payload for `deployment.deployed` events.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentDeployedEvent {
    /// ID of the deployment.
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,
    /// ID of the release associated with this deployment.
    #[serde(rename = "release_id")]
    pub release_id: String,
    #[serde(rename = "status")]
    pub status: models::DeploymentStatus,
    #[serde(rename = "activity_status")]
    pub activity_status: models::DeploymentActivityStatus,
    #[serde(rename = "error_status")]
    pub error_status: models::DeploymentErrorStatus,
    #[serde(rename = "target_status")]
    pub target_status: models::DeploymentTargetStatus,
    /// Timestamp of when the deployment was deployed.
    #[serde(rename = "deployed_at", skip_serializing_if = "Option::is_none")]
    pub deployed_at: Option<String>,
}

impl DeploymentDeployedEvent {
    /// Payload for `deployment.deployed` events.
    pub fn new(deployment_id: String, release_id: String, status: models::DeploymentStatus, activity_status: models::DeploymentActivityStatus, error_status: models::DeploymentErrorStatus, target_status: models::DeploymentTargetStatus) -> DeploymentDeployedEvent {
        DeploymentDeployedEvent {
            deployment_id,
            release_id,
            status,
            activity_status,
            error_status,
            target_status,
            deployed_at: None,
        }
    }
}

