/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceStatus : The status of the device. - Online: The miru agent is connected - Offline: The miru agent is disconnected (e.g. network issues, device is powered off, etc.) 
/// The status of the device. - Online: The miru agent is connected - Offline: The miru agent is disconnected (e.g. network issues, device is powered off, etc.) 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceStatus {
    #[serde(rename = "online")]
    DEVICE_STATUS_ONLINE,
    #[serde(rename = "offline")]
    DEVICE_STATUS_OFFLINE,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    DeviceStatusUnknown,
}

impl std::fmt::Display for DeviceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEVICE_STATUS_ONLINE => write!(f, "online"),
            Self::DEVICE_STATUS_OFFLINE => write!(f, "offline"),
            Self::DeviceStatusUnknown => write!(f, "unknown"),
        }
    }
}

impl Default for DeviceStatus {
    fn default() -> DeviceStatus {
        Self::DEVICE_STATUS_ONLINE
    }
}

