/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// The error code identifying the type of error.
    #[serde(rename = "code")]
    pub code: String,
    /// Additional parameters providing context about the error.
    #[serde(rename = "params")]
    pub params: std::collections::HashMap<String, serde_json::Value>,
    /// A human-readable message describing the error.
    #[serde(rename = "message")]
    pub message: String,
}

impl Error {
    pub fn new(
        code: String,
        params: std::collections::HashMap<String, serde_json::Value>,
        message: String,
    ) -> Error {
        Error {
            code,
            params,
            message,
        }
    }
}
