/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    /// The object type, which is always `event`.
    #[serde(rename = "object")]
    pub object: Object,
    /// Monotonically increasing event ID. Used as the SSE `id` field and for replay cursors.
    #[serde(rename = "id")]
    pub id: i64,
    /// Event type string in the format `{resource}.{action}`.
    #[serde(rename = "type")]
    pub r#type: String,
    /// Timestamp of when the event occurred.
    #[serde(rename = "occurred_at")]
    pub occurred_at: String,
    /// Event-specific payload. Shape varies by event type.
    #[serde(rename = "data")]
    pub data: serde_json::Value,
}

impl Event {
    pub fn new(object: Object, id: i64, r#type: String, occurred_at: String, data: serde_json::Value) -> Event {
        Event {
            object,
            id,
            r#type,
            occurred_at,
            data,
        }
    }
}
/// The object type, which is always `event`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "event")]
    Event,
}

impl Default for Object {
    fn default() -> Object {
        Self::Event
    }
}

