/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCommit {
    /// The object type, which is always `git_commit`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the git commit.
    #[serde(rename = "id")]
    pub id: String,
    /// The SHA hash of the git commit.
    #[serde(rename = "sha")]
    pub sha: String,
    /// The commit message.
    #[serde(rename = "message")]
    pub message: String,
    /// The URL of the git commit.
    #[serde(rename = "commit_url")]
    pub commit_url: String,
    /// Timestamp of when the git commit was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl GitCommit {
    pub fn new(
        object: Object,
        id: String,
        sha: String,
        message: String,
        commit_url: String,
        created_at: String,
    ) -> GitCommit {
        GitCommit {
            object,
            id,
            sha,
            message,
            commit_url,
            created_at,
        }
    }
}
/// The object type, which is always `git_commit`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "git_commit")]
    GitCommit,
}

impl Default for Object {
    fn default() -> Object {
        Self::GitCommit
    }
}
