/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Release {
    /// The object type, which is always `release`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the release.
    #[serde(rename = "id")]
    pub id: String,
    /// The version of the release.
    #[serde(rename = "version")]
    pub version: String,
    /// The ID of the git commit associated with this release.
    #[serde(rename = "git_commit_id", deserialize_with = "Option::deserialize")]
    pub git_commit_id: Option<String>,
    /// IDs of the file rules included in this release. Retrieve each file rule with `GET /file_rules/{file_rule_id}`.
    #[serde(rename = "file_rule_ids")]
    pub file_rule_ids: Vec<String>,
    /// Timestamp of when the release was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Release {
    pub fn new(object: Object, id: String, version: String, git_commit_id: Option<String>, file_rule_ids: Vec<String>, created_at: String) -> Release {
        Release {
            object,
            id,
            version,
            git_commit_id,
            file_rule_ids,
            created_at,
        }
    }
}
/// The object type, which is always `release`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "release")]
    Release,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    ObjectUnknown,
}

impl Default for Object {
    fn default() -> Object {
        Self::Release
    }
}

