/*
 * Miru Agent API
 *
 * The API between the Miru Agent and any external client living on the same device as the Miru Agent
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionResponse {
    /// The version of the agent.
    #[serde(rename = "version")]
    pub version: String,
    /// The git commit of the agent.
    #[serde(rename = "git_commit")]
    pub git_commit: String,
    /// The API version of the agent.
    #[serde(rename = "api_version")]
    pub api_version: String,
    /// The git commit of the API.
    #[serde(rename = "api_git_commit")]
    pub api_git_commit: String,
    /// The version of Rust.
    #[serde(rename = "rust_version")]
    pub rust_version: String,
    /// The build date of the agent.
    #[serde(rename = "build_date")]
    pub build_date: String,
    /// The operating system of the agent.
    #[serde(rename = "os")]
    pub os: String,
    /// The architecture of the agent.
    #[serde(rename = "arch")]
    pub arch: String,
}

impl VersionResponse {
    pub fn new(
        version: String,
        git_commit: String,
        api_version: String,
        api_git_commit: String,
        rust_version: String,
        build_date: String,
        os: String,
        arch: String,
    ) -> VersionResponse {
        VersionResponse {
            version,
            git_commit,
            api_version,
            api_git_commit,
            rust_version,
            build_date,
            os,
            arch,
        }
    }
}
