/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiVersion {
    #[serde(rename = "v0.5")]
    API_VERSION,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    ApiVersionUnknown,
}

impl std::fmt::Display for ApiVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::API_VERSION => write!(f, "v0.5"),
            Self::ApiVersionUnknown => write!(f, "unknown"),
        }
    }
}

impl Default for ApiVersion {
    fn default() -> ApiVersion {
        Self::API_VERSION
    }
}

