/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Arch : A CPU architecture, from the agent's build-time architecture vocabulary. Shared across resources (devices, config schemas, file rules). These are the canonical wire values. - `x86_64` - `aarch64` 
/// A CPU architecture, from the agent's build-time architecture vocabulary. Shared across resources (devices, config schemas, file rules). These are the canonical wire values. - `x86_64` - `aarch64` 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Arch {
    #[serde(rename = "x86_64")]
    ARCH_X86_64,
    #[serde(rename = "aarch64")]
    ARCH_AARCH64,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    ArchUnknown,
}

impl std::fmt::Display for Arch {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ARCH_X86_64 => write!(f, "x86_64"),
            Self::ARCH_AARCH64 => write!(f, "aarch64"),
            Self::ArchUnknown => write!(f, "unknown"),
        }
    }
}

impl Default for Arch {
    fn default() -> Arch {
        Self::ARCH_X86_64
    }
}

