/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseFileRule : A file rule declares which files on a device Miru manages and what to do with them: upload them to a bucket, delete the local copies once they are no longer needed, or both. `retention` is optional and marks the rules that delete: when it is absent the device keeps matching files indefinitely — Miru never deletes them — and when it is present the rule deletes each matching file once its retention guarantee ends. A rule that both deletes and uploads always states `retention.require_upload`, so whether local deletion waits for the upload is itself an explicit decision. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseFileRule {
    /// The object type, which is always `file_rule`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the file rule.
    #[serde(rename = "id")]
    pub id: String,
    /// A human-readable name for the file rule. Not unique within a workspace: file rules are immutable, so each authored revision mints a new rule and several rules may share a name. The name participates in the rule's digest, so renaming a rule mints a new rule.
    #[serde(rename = "name")]
    pub name: String,
    /// The digest of the file rule. File rules are immutable and deduplicated by digest within a workspace.
    #[serde(rename = "digest")]
    pub digest: String,
    #[serde(rename = "source")]
    pub source: Box<models::FileRuleSource>,
    /// Where matching files are uploaded. Absent when the rule only enforces local retention.
    #[serde(rename = "upload", skip_serializing_if = "Option::is_none")]
    pub upload: Option<Box<models::FileRuleUpload>>,
    /// Governs deletion of the local copies of matching files. Absent when the device keeps matching files indefinitely — Miru never deletes them; present when the rule deletes each matching file once its retention guarantee ends.
    #[serde(rename = "retention", skip_serializing_if = "Option::is_none")]
    pub retention: Option<Box<models::FileRuleRetention>>,
    /// Timestamp of when the file rule was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the file rule was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl BaseFileRule {
    /// A file rule declares which files on a device Miru manages and what to do with them: upload them to a bucket, delete the local copies once they are no longer needed, or both. `retention` is optional and marks the rules that delete: when it is absent the device keeps matching files indefinitely — Miru never deletes them — and when it is present the rule deletes each matching file once its retention guarantee ends. A rule that both deletes and uploads always states `retention.require_upload`, so whether local deletion waits for the upload is itself an explicit decision. 
    pub fn new(object: Object, id: String, name: String, digest: String, source: models::FileRuleSource, created_at: String, updated_at: String) -> BaseFileRule {
        BaseFileRule {
            object,
            id,
            name,
            digest,
            source: Box::new(source),
            upload: None,
            retention: None,
            created_at,
            updated_at,
        }
    }
}
/// The object type, which is always `file_rule`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "file_rule")]
    FileRule,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    ObjectUnknown,
}

impl Default for Object {
    fn default() -> Object {
        Self::FileRule
    }
}

