/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseUploadRule {
    /// The object type, which is always `upload_rule`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the upload rule.
    #[serde(rename = "id")]
    pub id: String,
    /// ID of the upload collection this rule belongs to.
    #[serde(rename = "upload_collection_id")]
    pub upload_collection_id: String,
    /// The name of the upload collection this rule belongs to.
    #[serde(rename = "upload_collection_name")]
    pub upload_collection_name: String,
    /// The digest of the upload rule. Upload rules are immutable and deduplicated by digest within an upload collection.
    #[serde(rename = "digest")]
    pub digest: String,
    #[serde(rename = "source")]
    pub source: Box<models::UploadRuleSource>,
    #[serde(rename = "destination")]
    pub destination: Box<models::UploadRuleDestination>,
    /// Timestamp of when the upload rule was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the upload rule was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl BaseUploadRule {
    pub fn new(object: Object, id: String, upload_collection_id: String, upload_collection_name: String, digest: String, source: models::UploadRuleSource, destination: models::UploadRuleDestination, created_at: String, updated_at: String) -> BaseUploadRule {
        BaseUploadRule {
            object,
            id,
            upload_collection_id,
            upload_collection_name,
            digest,
            source: Box::new(source),
            destination: Box::new(destination),
            created_at,
            updated_at,
        }
    }
}
/// The object type, which is always `upload_rule`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "upload_rule")]
    UploadRule,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    ObjectUnknown,
}

impl Default for Object {
    fn default() -> Object {
        Self::UploadRule
    }
}

