/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseConfigInstance {
    /// The object type, which is always `config_instance`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the config instance.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the config type.
    #[serde(rename = "config_type_name")]
    pub config_type_name: String,
    /// The absolute file system path where this config instance is written.
    #[serde(rename = "filepath")]
    pub filepath: String,
    /// The key of the config schema slot this instance is bound to. Must match the `key` of one of the slots declared by this instance's config schema.
    #[serde(rename = "slot_key")]
    pub slot_key: String,
    /// The timestamp of when the config instance was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// ID of the config schema which the config instance must adhere to.
    #[serde(rename = "config_schema_id")]
    pub config_schema_id: String,
    /// ID of the config type which the config instance (and its schema) is a part of.
    #[serde(rename = "config_type_id")]
    pub config_type_id: String,
}

impl BaseConfigInstance {
    pub fn new(object: Object, id: String, config_type_name: String, filepath: String, slot_key: String, created_at: String, config_schema_id: String, config_type_id: String) -> BaseConfigInstance {
        BaseConfigInstance {
            object,
            id,
            config_type_name,
            filepath,
            slot_key,
            created_at,
            config_schema_id,
            config_type_id,
        }
    }
}
/// The object type, which is always `config_instance`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "config_instance")]
    ConfigInstance,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    ObjectUnknown,
}

impl Default for Object {
    fn default() -> Object {
        Self::ConfigInstance
    }
}

