/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseRelease {
    /// The object type, which is always `release`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the release.
    #[serde(rename = "id")]
    pub id: String,
    /// The version of the release.
    #[serde(rename = "version")]
    pub version: String,
    /// The ID of the git commit associated with this release.
    #[serde(rename = "git_commit_id", deserialize_with = "Option::deserialize")]
    pub git_commit_id: Option<String>,
    /// Timestamp of when the release was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the release was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl BaseRelease {
    pub fn new(
        object: Object,
        id: String,
        version: String,
        git_commit_id: Option<String>,
        created_at: String,
        updated_at: String,
    ) -> BaseRelease {
        BaseRelease {
            object,
            id,
            version,
            git_commit_id,
            created_at,
            updated_at,
        }
    }
}
/// The object type, which is always `release`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "release")]
    Release,
}

impl Default for Object {
    fn default() -> Object {
        Self::Release
    }
}
