/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUploadRequest {
    /// ID of the upload rule that selected this file.
    #[serde(rename = "upload_rule_id")]
    pub upload_rule_id: String,
    /// Source-side details of the file on the device.
    #[serde(rename = "source")]
    pub source: Box<models::UploadSource>,
    /// The digest of the file being uploaded.
    #[serde(rename = "digest")]
    pub digest: String,
    /// The size of the file in bytes.
    #[serde(rename = "size")]
    pub size: i64,
    /// Whether the file was incomplete when collected (e.g. it was never closed cleanly / has no finalization marker). Sets the upload's `incomplete` flag. Defaults to false.
    #[serde(rename = "incomplete", skip_serializing_if = "Option::is_none")]
    pub incomplete: Option<bool>,
    /// ID of the release the device is currently on.
    #[serde(rename = "release_id")]
    pub release_id: String,
    /// ID of the deployment the device is currently on.
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,
}

impl CreateUploadRequest {
    pub fn new(upload_rule_id: String, source: models::UploadSource, digest: String, size: i64, release_id: String, deployment_id: String) -> CreateUploadRequest {
        CreateUploadRequest {
            upload_rule_id,
            source: Box::new(source),
            digest,
            size,
            incomplete: None,
            release_id,
            deployment_id,
        }
    }
}

