/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentExpansion {
    #[serde(rename = "release")]
    DEPLOYMENT_EXPAND_RELEASE,
    #[serde(rename = "config_instances")]
    DEPLOYMENT_EXPAND_CONFIG_INSTANCES,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    DeploymentExpansionUnknownValue,
}

impl std::fmt::Display for DeploymentExpansion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_EXPAND_RELEASE => write!(f, "release"),
            Self::DEPLOYMENT_EXPAND_CONFIG_INSTANCES => write!(f, "config_instances"),
            Self::DeploymentExpansionUnknownValue => write!(f, "unknown_value"),
        }
    }
}

impl Default for DeploymentExpansion {
    fn default() -> DeploymentExpansion {
        Self::DEPLOYMENT_EXPAND_RELEASE
    }
}

