/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentErrorStatus : Last known error state of the deployment.  `none` means there are no errors.  `retrying` means an error has been encountered and the agent is retrying to reach the target status.  `failed` means a fatal error has been encountered; the deployment is archived and, if deployed, removed from the device. 
/// Last known error state of the deployment.  `none` means there are no errors.  `retrying` means an error has been encountered and the agent is retrying to reach the target status.  `failed` means a fatal error has been encountered; the deployment is archived and, if deployed, removed from the device. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentErrorStatus {
    #[serde(rename = "none")]
    DEPLOYMENT_ERROR_STATUS_NONE,
    #[serde(rename = "failed")]
    DEPLOYMENT_ERROR_STATUS_FAILED,
    #[serde(rename = "retrying")]
    DEPLOYMENT_ERROR_STATUS_RETRYING,
    /// Catch-all for enum values added by the backend after this agent was
    /// built. `#[serde(other)]` makes unrecognized strings deserialize here
    /// instead of failing the entire payload (forward compatibility). This
    /// variant is never serialized in practice; the agent only sends values
    /// built from its own domain enums.
    #[serde(other)]
    DEPLOYMENT_ERROR_STATUS_UNKNOWN_VALUE,

}

impl std::fmt::Display for DeploymentErrorStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_ERROR_STATUS_NONE => write!(f, "none"),
            Self::DEPLOYMENT_ERROR_STATUS_FAILED => write!(f, "failed"),
            Self::DEPLOYMENT_ERROR_STATUS_RETRYING => write!(f, "retrying"),
            Self::DEPLOYMENT_ERROR_STATUS_UNKNOWN_VALUE => write!(f, "unknown_value"),
        }
    }
}

impl Default for DeploymentErrorStatus {
    fn default() -> DeploymentErrorStatus {
        Self::DEPLOYMENT_ERROR_STATUS_NONE
    }
}

