/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentActivityStatus : Last known activity state of the deployment.  `drifted` means the device's configurations have drifted since this deployment was staged, and the deployment needs to be reviewed before it can be deployed.  `staged` means the deployment is ready to be deployed.  `queued` means the deployment's config instances are waiting to be received by the device and will be deployed as soon as the device is online.  `deployed` means the deployment's config instances are currently available for consumption on the device.  `removing` means the deployment's config instances are being removed from the device.  `archived` means the deployment is available for historical reference but cannot be deployed and is not active on the device. 
/// Last known activity state of the deployment.  `drifted` means the device's configurations have drifted since this deployment was staged, and the deployment needs to be reviewed before it can be deployed.  `staged` means the deployment is ready to be deployed.  `queued` means the deployment's config instances are waiting to be received by the device and will be deployed as soon as the device is online.  `deployed` means the deployment's config instances are currently available for consumption on the device.  `removing` means the deployment's config instances are being removed from the device.  `archived` means the deployment is available for historical reference but cannot be deployed and is not active on the device. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentActivityStatus {
    #[serde(rename = "drifted")]
    DEPLOYMENT_ACTIVITY_STATUS_DRIFTED,
    #[serde(rename = "staged")]
    DEPLOYMENT_ACTIVITY_STATUS_STAGED,
    #[serde(rename = "queued")]
    DEPLOYMENT_ACTIVITY_STATUS_QUEUED,
    #[serde(rename = "deployed")]
    DEPLOYMENT_ACTIVITY_STATUS_DEPLOYED,
    #[serde(rename = "removing")]
    DEPLOYMENT_ACTIVITY_STATUS_REMOVING,
    #[serde(rename = "archived")]
    DEPLOYMENT_ACTIVITY_STATUS_ARCHIVED,
    /// Catch-all for enum values added by the backend after this agent was
    /// built. `#[serde(other)]` makes unrecognized strings deserialize here
    /// instead of failing the entire payload (forward compatibility). This
    /// variant is never serialized in practice; the agent only sends values
    /// built from its own domain enums.
    #[serde(other)]
    DEPLOYMENT_ACTIVITY_STATUS_UNKNOWN_VALUE,

}

impl std::fmt::Display for DeploymentActivityStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_ACTIVITY_STATUS_DRIFTED => write!(f, "drifted"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_STAGED => write!(f, "staged"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_QUEUED => write!(f, "queued"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_REMOVING => write!(f, "removing"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_ARCHIVED => write!(f, "archived"),
            Self::DEPLOYMENT_ACTIVITY_STATUS_UNKNOWN_VALUE => write!(f, "unknown_value"),
        }
    }
}

impl Default for DeploymentActivityStatus {
    fn default() -> DeploymentActivityStatus {
        Self::DEPLOYMENT_ACTIVITY_STATUS_DRIFTED
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_values_round_trip_identically() {
        for (variant, wire) in [
            (DeploymentActivityStatus::DEPLOYMENT_ACTIVITY_STATUS_DRIFTED, "drifted"),
            (DeploymentActivityStatus::DEPLOYMENT_ACTIVITY_STATUS_STAGED, "staged"),
            (DeploymentActivityStatus::DEPLOYMENT_ACTIVITY_STATUS_QUEUED, "queued"),
            (DeploymentActivityStatus::DEPLOYMENT_ACTIVITY_STATUS_DEPLOYED, "deployed"),
            (DeploymentActivityStatus::DEPLOYMENT_ACTIVITY_STATUS_REMOVING, "removing"),
            (DeploymentActivityStatus::DEPLOYMENT_ACTIVITY_STATUS_ARCHIVED, "archived"),
        ] {
            let json = format!("\"{wire}\"");
            let de: DeploymentActivityStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(de, variant);
            assert_eq!(serde_json::to_string(&variant).unwrap(), json);
            assert_eq!(variant.to_string(), wire);
        }
    }

    #[test]
    fn unknown_value_deserializes_into_catch_all_instead_of_erroring() {
        let de: DeploymentActivityStatus =
            serde_json::from_str("\"some_future_status\"").unwrap();
        assert_eq!(de, DeploymentActivityStatus::DEPLOYMENT_ACTIVITY_STATUS_UNKNOWN_VALUE);
    }
}

