/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentTargetStatus : Desired state of the deployment.  `staged` means the deployment is ready to be deployed.  `deployed` means all config instances in the deployment are available for consumption on the device.  `archived` means the deployment is available for historical reference but cannot be deployed and is not active on the device. 
/// Desired state of the deployment.  `staged` means the deployment is ready to be deployed.  `deployed` means all config instances in the deployment are available for consumption on the device.  `archived` means the deployment is available for historical reference but cannot be deployed and is not active on the device. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentTargetStatus {
    #[serde(rename = "staged")]
    DEPLOYMENT_TARGET_STATUS_STAGED,
    #[serde(rename = "deployed")]
    DEPLOYMENT_TARGET_STATUS_DEPLOYED,
    #[serde(rename = "archived")]
    DEPLOYMENT_TARGET_STATUS_ARCHIVED,

}

impl std::fmt::Display for DeploymentTargetStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEPLOYMENT_TARGET_STATUS_STAGED => write!(f, "staged"),
            Self::DEPLOYMENT_TARGET_STATUS_DEPLOYED => write!(f, "deployed"),
            Self::DEPLOYMENT_TARGET_STATUS_ARCHIVED => write!(f, "archived"),
        }
    }
}

impl Default for DeploymentTargetStatus {
    fn default() -> DeploymentTargetStatus {
        Self::DEPLOYMENT_TARGET_STATUS_STAGED
    }
}

