/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Deployment {
    /// The object type, which is always `deployment`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the deployment.
    #[serde(rename = "id")]
    pub id: String,
    /// The description of the deployment.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "status")]
    pub status: models::DeploymentStatus,
    #[serde(rename = "activity_status")]
    pub activity_status: models::DeploymentActivityStatus,
    #[serde(rename = "error_status")]
    pub error_status: models::DeploymentErrorStatus,
    #[serde(rename = "target_status")]
    pub target_status: models::DeploymentTargetStatus,
    /// ID of the device.
    #[serde(rename = "device_id")]
    pub device_id: String,
    /// ID of the release.
    #[serde(rename = "release_id")]
    pub release_id: String,
    /// Timestamp of when the device release was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the device release was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Expand the release using 'expand=release' in the query string.
    #[serde(rename = "release", skip_serializing_if = "Option::is_none")]
    pub release: Option<Box<models::Release>>,
    /// Expand the config instances using 'expand=config_instances' in the query string.
    #[serde(rename = "config_instances", skip_serializing_if = "Option::is_none")]
    pub config_instances: Option<Vec<models::ConfigInstance>>,
}

impl Deployment {
    pub fn new(object: Object, id: String, description: String, status: models::DeploymentStatus, activity_status: models::DeploymentActivityStatus, error_status: models::DeploymentErrorStatus, target_status: models::DeploymentTargetStatus, device_id: String, release_id: String, created_at: String, updated_at: String) -> Deployment {
        Deployment {
            object,
            id,
            description,
            status,
            activity_status,
            error_status,
            target_status,
            device_id,
            release_id,
            created_at,
            updated_at,
            release: None,
            config_instances: None,
        }
    }
}
/// The object type, which is always `deployment`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "deployment")]
    Deployment,
}

impl Default for Object {
    fn default() -> Object {
        Self::Deployment
    }
}

#[cfg(test)]
mod forward_compat_tests {
    use crate::models::Deployment;

    #[test]
    fn deployment_payload_with_unknown_activity_status_still_deserializes() {
        // Build the JSON from a known-good Deployment, then overwrite
        // activity_status with an unknown string, so the test stays in sync
        // with required fields without hand-maintaining the whole payload.
        let mut value = serde_json::to_value(Deployment::default())
            .expect("serialize sample deployment");
        value["activity_status"] = serde_json::Value::String("some_future_status".into());
        let de: Deployment = serde_json::from_value(value)
            .expect("payload with unknown activity_status must still deserialize");
        assert_eq!(
            de.activity_status,
            crate::models::DeploymentActivityStatus::DEPLOYMENT_ACTIVITY_STATUS_UNKNOWN_VALUE
        );
    }
}

