/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceStatus : The status of the device. - Inactive: The miru agent has not yet been installed / authenticated - Activating: The miru agent is currently being installed / authenticated (should only last for a few seconds) - Online: The miru agent has successfully pinged the server within the last 60 seconds. - Offline: The miru agent has not successfully pinged the server within the last 60 seconds (e.g. network issues, device is powered off, etc.) 
/// The status of the device. - Inactive: The miru agent has not yet been installed / authenticated - Activating: The miru agent is currently being installed / authenticated (should only last for a few seconds) - Online: The miru agent has successfully pinged the server within the last 60 seconds. - Offline: The miru agent has not successfully pinged the server within the last 60 seconds (e.g. network issues, device is powered off, etc.) 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceStatus {
    #[serde(rename = "inactive")]
    DEVICE_STATUS_INACTIVE,
    #[serde(rename = "activating")]
    DEVICE_STATUS_ACTIVATING,
    #[serde(rename = "online")]
    DEVICE_STATUS_ONLINE,
    #[serde(rename = "offline")]
    DEVICE_STATUS_OFFLINE,
    /// Catch-all for enum values added by the backend after this agent was
    /// built. `#[serde(other)]` makes unrecognized strings deserialize here
    /// instead of failing the entire payload (forward compatibility). This
    /// variant is never serialized in practice; the agent only sends values
    /// built from its own domain enums.
    #[serde(other)]
    DEVICE_STATUS_UNKNOWN_VALUE,

}

impl std::fmt::Display for DeviceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DEVICE_STATUS_INACTIVE => write!(f, "inactive"),
            Self::DEVICE_STATUS_ACTIVATING => write!(f, "activating"),
            Self::DEVICE_STATUS_ONLINE => write!(f, "online"),
            Self::DEVICE_STATUS_OFFLINE => write!(f, "offline"),
            Self::DEVICE_STATUS_UNKNOWN_VALUE => write!(f, "unknown_value"),
        }
    }
}

impl Default for DeviceStatus {
    fn default() -> DeviceStatus {
        Self::DEVICE_STATUS_INACTIVE
    }
}

