/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Device {
    /// The object type, which is always `device`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the device.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the device.
    #[serde(rename = "name")]
    pub name: String,
    /// A free-form description of the device.
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    #[serde(rename = "status")]
    pub status: models::DeviceStatus,
    /// The version of the agent the device is running.
    #[serde(rename = "agent_version", deserialize_with = "Option::deserialize")]
    pub agent_version: Option<String>,
    /// The operating system family the device is running (`linux` or `windows`), reported by the agent. This is the machine-readable OS kind, distinct from the human-readable `os_version` string.
    #[serde(rename = "os", deserialize_with = "Option::deserialize")]
    pub os: Option<models::Os>,
    /// The hostname of the device as reported by the agent.
    #[serde(rename = "hostname", deserialize_with = "Option::deserialize")]
    pub hostname: Option<String>,
    /// The CPU architecture the device is running (`x86_64` or `aarch64`), reported by the agent.
    #[serde(rename = "arch", deserialize_with = "Option::deserialize")]
    pub arch: Option<models::Arch>,
    /// The human-readable long operating system version string reported by the agent (for example `Ubuntu 22.04` or `Windows 11 Pro`). Distinct from the machine-readable `os` family.
    #[serde(rename = "os_version", deserialize_with = "Option::deserialize")]
    pub os_version: Option<String>,
    /// The operating system kernel version string reported by the agent.
    #[serde(rename = "kernel_version", deserialize_with = "Option::deserialize")]
    pub kernel_version: Option<String>,
    /// Timestamp of when the device was last made an initial connection (this is not the same as the last time the device was seen).
    #[serde(rename = "last_connected_at", deserialize_with = "Option::deserialize")]
    pub last_connected_at: Option<String>,
    /// Timestamp of when the device was last disconnected (this is not the same as the last time the device was seen).
    #[serde(rename = "last_disconnected_at", deserialize_with = "Option::deserialize")]
    pub last_disconnected_at: Option<String>,
    /// Timestamp of when the device was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the device was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Session ID of the device.
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl Device {
    pub fn new(object: Object, id: String, name: String, description: Option<String>, status: models::DeviceStatus, agent_version: Option<String>, os: Option<models::Os>, hostname: Option<String>, arch: Option<models::Arch>, os_version: Option<String>, kernel_version: Option<String>, last_connected_at: Option<String>, last_disconnected_at: Option<String>, created_at: String, updated_at: String, session_id: String) -> Device {
        Device {
            object,
            id,
            name,
            description,
            status,
            agent_version,
            os,
            hostname,
            arch,
            os_version,
            kernel_version,
            last_connected_at,
            last_disconnected_at,
            created_at,
            updated_at,
            session_id,
        }
    }
}
/// The object type, which is always `device`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "device")]
    Device,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    ObjectUnknown,
}

impl Default for Object {
    fn default() -> Object {
        Self::Device
    }
}

