/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Device {
    /// The object type, which is always `device`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the device.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the device.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: models::DeviceStatus,
    /// The version of the agent the device is running.
    #[serde(rename = "agent_version", deserialize_with = "Option::deserialize")]
    pub agent_version: Option<String>,
    /// Timestamp of when the device was last made an initial connection (this is not the same as the last time the device was seen).
    #[serde(rename = "last_connected_at", deserialize_with = "Option::deserialize")]
    pub last_connected_at: Option<String>,
    /// Timestamp of when the device was last disconnected (this is not the same as the last time the device was seen).
    #[serde(rename = "last_disconnected_at", deserialize_with = "Option::deserialize")]
    pub last_disconnected_at: Option<String>,
    /// Timestamp of when the device was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the device was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Session ID of the device.
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl Device {
    pub fn new(object: Object, id: String, name: String, status: models::DeviceStatus, agent_version: Option<String>, last_connected_at: Option<String>, last_disconnected_at: Option<String>, created_at: String, updated_at: String, session_id: String) -> Device {
        Device {
            object,
            id,
            name,
            status,
            agent_version,
            last_connected_at,
            last_disconnected_at,
            created_at,
            updated_at,
            session_id,
        }
    }
}
/// The object type, which is always `device`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "device")]
    Device,
}

impl Default for Object {
    fn default() -> Object {
        Self::Device
    }
}

#[cfg(test)]
mod forward_compat_tests {
    use crate::models::Device;

    #[test]
    fn device_payload_with_unknown_status_still_deserializes() {
        // Build the JSON from a known-good Device, then overwrite status with
        // an unknown string, so the test stays in sync with required fields
        // without hand-maintaining the whole payload.
        let mut value = serde_json::to_value(Device::default())
            .expect("serialize sample device");
        value["status"] = serde_json::Value::String("some_future_status".into());
        let de: Device = serde_json::from_value(value)
            .expect("payload with unknown status must still deserialize");
        assert_eq!(
            de.status,
            crate::models::DeviceStatus::DEVICE_STATUS_UNKNOWN_VALUE
        );
    }
}

