/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DplSearch : **Internal server use only**: an enum of possible search fields. 
/// **Internal server use only**: an enum of possible search fields. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DplSearch {
    #[serde(rename = "activity_status")]
    DPL_SEARCH_ACTIVITY_STATUS,

}

impl std::fmt::Display for DplSearch {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DPL_SEARCH_ACTIVITY_STATUS => write!(f, "activity_status"),
        }
    }
}

impl Default for DplSearch {
    fn default() -> DplSearch {
        Self::DPL_SEARCH_ACTIVITY_STATUS
    }
}

