/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileRuleRetention : The retention block a file rule carries when it deletes local files; a rule without one keeps matching files indefinitely and Miru never deletes them. Retention operates in two phases. The retention guarantee ends once a matching file goes quiescent — its size and modification time have stayed unchanged for `source.stability_window_secs` — and, when `require_upload` is `true`, once its upload has been durably confirmed; the file is then eligible for deletion, and callers may no longer rely on it being present. `ttl_secs` schedules the enforcement that follows: how long the file lives on after the guarantee ends before the device deletes it. Both phases keep running on the device even when no release is deployed, so tearing down a deployment does not silently stop reclaiming disk. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileRuleRetention {
    /// Whether a file must have its upload durably confirmed before it may be deleted. Present exactly when the rule has an `upload` block. When `true`, a slow or failing upload keeps the local file: the device abandons an upload after 9 attempts, so a permanently failing upload retains the file indefinitely. When `false`, the upload is best-effort: the file may be deleted once eligible even if its upload has not completed, and an unfinished upload is abandoned.
    #[serde(rename = "require_upload", skip_serializing_if = "Option::is_none")]
    pub require_upload: Option<bool>,
    /// How long, in seconds, the file lives on after it becomes eligible for deletion. The clock starts when the retention guarantee ends, not when the file was written: this schedules enforcement of a guarantee that has already ended, so it defers the deletion, not the end of the guarantee. `0` means the file is deleted as soon as it becomes eligible.
    #[serde(rename = "ttl_secs")]
    pub ttl_secs: i64,
}

impl FileRuleRetention {
    /// The retention block a file rule carries when it deletes local files; a rule without one keeps matching files indefinitely and Miru never deletes them. Retention operates in two phases. The retention guarantee ends once a matching file goes quiescent — its size and modification time have stayed unchanged for `source.stability_window_secs` — and, when `require_upload` is `true`, once its upload has been durably confirmed; the file is then eligible for deletion, and callers may no longer rely on it being present. `ttl_secs` schedules the enforcement that follows: how long the file lives on after the guarantee ends before the device deletes it. Both phases keep running on the device even when no release is deployed, so tearing down a deployment does not silently stop reclaiming disk. 
    pub fn new(ttl_secs: i64) -> FileRuleRetention {
        FileRuleRetention {
            require_upload: None,
            ttl_secs,
        }
    }
}

