/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileRuleUpload {
    /// ID of the upload collection the resulting uploads are grouped into.
    #[serde(rename = "upload_collection_id")]
    pub upload_collection_id: String,
    /// The name of the upload collection the resulting uploads are grouped into.
    #[serde(rename = "upload_collection_name")]
    pub upload_collection_name: String,
    /// ID of the bucket this rule uploads to.
    #[serde(rename = "bucket_id")]
    pub bucket_id: String,
    /// Name of the bucket this rule uploads to.
    #[serde(rename = "bucket_name")]
    pub bucket_name: String,
    /// The object-path template the collected file is written to. Must contain `{upload_id}` so every upload lands on a distinct object key, be at most 1024 bytes, have balanced braces, and contain no `..` segments and no empty path segments. The supported variables are `{device_id}`, `{device_name}`, `{file_name}`, `{upload_id}`, `{year}`, `{month}`, `{day}`, `{hour}`, and `{minute}`.
    #[serde(rename = "path")]
    pub path: String,
}

impl FileRuleUpload {
    pub fn new(upload_collection_id: String, upload_collection_name: String, bucket_id: String, bucket_name: String, path: String) -> FileRuleUpload {
        FileRuleUpload {
            upload_collection_id,
            upload_collection_name,
            bucket_id,
            bucket_name,
            path,
        }
    }
}

