/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GcsUploadCredentials : Short-lived Google Cloud Storage credentials for the broker upload flow. The backend impersonates the bucket's service account and downscopes the token with a Credential Access Boundary (CAB) to `storage.objects.create` on the exact object name, so the device can drive a native resumable upload directly. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GcsUploadCredentials {
    /// The storage access scheme, which is always `gcs` for these credentials.
    #[serde(rename = "scheme")]
    pub scheme: Scheme,
    /// A downscoped GCS OAuth2 bearer token the device sends as `Authorization: Bearer <token>` on the resumable upload.
    #[serde(rename = "access_token")]
    pub access_token: String,
    /// Timestamp after which the access token is no longer valid.
    #[serde(rename = "expires_at")]
    pub expires_at: String,
}

impl GcsUploadCredentials {
    /// Short-lived Google Cloud Storage credentials for the broker upload flow. The backend impersonates the bucket's service account and downscopes the token with a Credential Access Boundary (CAB) to `storage.objects.create` on the exact object name, so the device can drive a native resumable upload directly. 
    pub fn new(scheme: Scheme, access_token: String, expires_at: String) -> GcsUploadCredentials {
        GcsUploadCredentials {
            scheme,
            access_token,
            expires_at,
        }
    }
}
/// The storage access scheme, which is always `gcs` for these credentials.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "gcs")]
    Gcs,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    SchemeUnknown,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::Gcs
    }
}

