/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GitRepositoryType {
    #[serde(rename = "github")]
    GIT_REPO_TYPE_GITHUB,
    #[serde(rename = "gitlab")]
    GIT_REPO_TYPE_GITLAB,
    #[serde(rename = "bitbucket")]
    GIT_REPO_TYPE_BITBUCKET,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    GitRepositoryTypeUnknown,
}

impl std::fmt::Display for GitRepositoryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GIT_REPO_TYPE_GITHUB => write!(f, "github"),
            Self::GIT_REPO_TYPE_GITLAB => write!(f, "gitlab"),
            Self::GIT_REPO_TYPE_BITBUCKET => write!(f, "bitbucket"),
            Self::GitRepositoryTypeUnknown => write!(f, "unknown"),
        }
    }
}

impl Default for GitRepositoryType {
    fn default() -> GitRepositoryType {
        Self::GIT_REPO_TYPE_GITHUB
    }
}

