/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GitRepositoryType {
    #[serde(rename = "github")]
    GIT_REPO_TYPE_GITHUB,
    #[serde(rename = "gitlab")]
    GIT_REPO_TYPE_GITLAB,
    #[serde(rename = "bitbucket")]
    GIT_REPO_TYPE_BITBUCKET,
    /// Catch-all for enum values added by the backend after this agent was
    /// built. `#[serde(other)]` makes unrecognized strings deserialize here
    /// instead of failing the entire payload (forward compatibility). This
    /// variant is never serialized in practice; the agent only sends values
    /// built from its own domain enums.
    #[serde(other)]
    GIT_REPO_TYPE_UNKNOWN_VALUE,

}

impl std::fmt::Display for GitRepositoryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GIT_REPO_TYPE_GITHUB => write!(f, "github"),
            Self::GIT_REPO_TYPE_GITLAB => write!(f, "gitlab"),
            Self::GIT_REPO_TYPE_BITBUCKET => write!(f, "bitbucket"),
            Self::GIT_REPO_TYPE_UNKNOWN_VALUE => write!(f, "unknown_value"),
        }
    }
}

impl Default for GitRepositoryType {
    fn default() -> GitRepositoryType {
        Self::GIT_REPO_TYPE_GITHUB
    }
}

