/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstanceFormat {
    #[serde(rename = "json")]
    INSTANCE_FORMAT_JSON,
    #[serde(rename = "yaml")]
    INSTANCE_FORMAT_YAML,
    #[serde(rename = "jsonc")]
    INSTANCE_FORMAT_JSONC,

}

impl std::fmt::Display for InstanceFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::INSTANCE_FORMAT_JSON => write!(f, "json"),
            Self::INSTANCE_FORMAT_YAML => write!(f, "yaml"),
            Self::INSTANCE_FORMAT_JSONC => write!(f, "jsonc"),
        }
    }
}

impl Default for InstanceFormat {
    fn default() -> InstanceFormat {
        Self::INSTANCE_FORMAT_JSON
    }
}

