/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceContent {
    #[serde(rename = "format")]
    pub format: models::InstanceFormat,
    /// The configuration values associated with the config instance.
    #[serde(rename = "data")]
    pub data: String,
}

impl InstanceContent {
    pub fn new(format: models::InstanceFormat, data: String) -> InstanceContent {
        InstanceContent { format, data }
    }
}
