/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueDeviceTokenRequest {
    #[serde(rename = "claims")]
    pub claims: Box<models::IssueDeviceClaims>,
    /// The cryptographic signature of the claims.
    #[serde(rename = "signature")]
    pub signature: String,
}

impl IssueDeviceTokenRequest {
    pub fn new(claims: models::IssueDeviceClaims, signature: String) -> IssueDeviceTokenRequest {
        IssueDeviceTokenRequest {
            claims: Box::new(claims),
            signature,
        }
    }
}

