/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Os : An operating system family, from the agent's build-time OS vocabulary. Shared across resources (devices, config schemas, file rules). This is the machine-readable OS kind, distinct from a human-readable version string. - `linux` - `windows` 
/// An operating system family, from the agent's build-time OS vocabulary. Shared across resources (devices, config schemas, file rules). This is the machine-readable OS kind, distinct from a human-readable version string. - `linux` - `windows` 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Os {
    #[serde(rename = "linux")]
    OS_LINUX,
    #[serde(rename = "windows")]
    OS_WINDOWS,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    OsUnknown,
}

impl std::fmt::Display for Os {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OS_LINUX => write!(f, "linux"),
            Self::OS_WINDOWS => write!(f, "windows"),
            Self::OsUnknown => write!(f, "unknown"),
        }
    }
}

impl Default for Os {
    fn default() -> Os {
        Self::OS_LINUX
    }
}

