/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresignedUpload {
    /// ID of the upload ledger entry created for this request.
    #[serde(rename = "upload_id")]
    pub upload_id: String,
    /// The short-lived V4-presigned PUT URL the device uploads the file to.
    #[serde(rename = "upload_url")]
    pub upload_url: String,
    /// The object path in the destination bucket. Carries the device's verified ID.
    #[serde(rename = "object_key")]
    pub object_key: String,
    /// Timestamp after which the presigned URL is no longer valid.
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    #[serde(rename = "required_headers")]
    pub required_headers: Box<models::UploadRequiredHeaders>,
    /// True if a durable upload with the same digest already exists, in which case the device may skip the PUT.
    #[serde(rename = "already_uploaded")]
    pub already_uploaded: bool,
}

impl PresignedUpload {
    pub fn new(upload_id: String, upload_url: String, object_key: String, expires_at: String, required_headers: models::UploadRequiredHeaders, already_uploaded: bool) -> PresignedUpload {
        PresignedUpload {
            upload_id,
            upload_url,
            object_key,
            expires_at,
            required_headers: Box::new(required_headers),
            already_uploaded,
        }
    }
}

