/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProvisionDeviceRequest : Provision a device using a provisioning token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisionDeviceRequest {
    /// The public key in PEM format.
    #[serde(rename = "public_key_pem")]
    pub public_key_pem: String,
    /// The version of the agent the device is running.
    #[serde(rename = "agent_version")]
    pub agent_version: String,
    /// The name to assign to the device.
    #[serde(rename = "name")]
    pub name: String,
}

impl ProvisionDeviceRequest {
    /// Provision a device using a provisioning token.
    pub fn new(public_key_pem: String, agent_version: String, name: String) -> ProvisionDeviceRequest {
        ProvisionDeviceRequest {
            public_key_pem,
            agent_version,
            name,
        }
    }
}

