/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProvisionDeviceRequest : Provision a device using a provisioning token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisionDeviceRequest {
    /// The public key in PEM format.
    #[serde(rename = "public_key_pem")]
    pub public_key_pem: String,
    /// The version of the agent the device is running.
    #[serde(rename = "agent_version")]
    pub agent_version: String,
    /// The name to assign to the device. Only meaningful for the `create` capability; ignored by `activate` and `reactivate` because the device already has a name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ProvisionDeviceRequest {
    /// Provision a device using a provisioning token.
    pub fn new(public_key_pem: String, agent_version: String) -> ProvisionDeviceRequest {
        ProvisionDeviceRequest {
            public_key_pem,
            agent_version,
            name: None,
        }
    }
}

