/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReleaseVersion {
    #[serde(rename = "v0.4.0")]
    RELEASE_VERSION,

}

impl std::fmt::Display for ReleaseVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RELEASE_VERSION => write!(f, "v0.4.0"),
        }
    }
}

impl Default for ReleaseVersion {
    fn default() -> ReleaseVersion {
        Self::RELEASE_VERSION
    }
}

