/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReleaseExpansion {
    #[serde(rename = "upload_rules")]
    RELEASE_EXPAND_UPLOAD_RULES,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    ReleaseExpansionUnknown,
}

impl std::fmt::Display for ReleaseExpansion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RELEASE_EXPAND_UPLOAD_RULES => write!(f, "upload_rules"),
            Self::ReleaseExpansionUnknown => write!(f, "unknown"),
        }
    }
}

impl Default for ReleaseExpansion {
    fn default() -> ReleaseExpansion {
        Self::RELEASE_EXPAND_UPLOAD_RULES
    }
}

