/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// S3UploadCredentials : Short-lived AWS S3 session credentials for the broker upload flow. The backend vends session credentials scoped to `s3:PutObject` (plus the multipart actions) on the exact object key. The device drives a native S3 multipart upload with the standard AWS S3 SDK, configured from `region` plus the access key / secret / session token; the SDK derives the endpoint from the region. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3UploadCredentials {
    /// The storage access scheme, which is always `s3` for these credentials.
    #[serde(rename = "scheme")]
    pub scheme: Scheme,
    /// The STS session access key ID.
    #[serde(rename = "access_key_id")]
    pub access_key_id: String,
    /// The STS session secret access key.
    #[serde(rename = "secret_access_key")]
    pub secret_access_key: String,
    /// The STS session token that must accompany the access key pair.
    #[serde(rename = "session_token")]
    pub session_token: String,
    /// The AWS region of the bucket, used for the S3 endpoint and SigV4 signing.
    #[serde(rename = "region")]
    pub region: String,
    /// Timestamp after which the session credentials are no longer valid.
    #[serde(rename = "expires_at")]
    pub expires_at: String,
}

impl S3UploadCredentials {
    /// Short-lived AWS S3 session credentials for the broker upload flow. The backend vends session credentials scoped to `s3:PutObject` (plus the multipart actions) on the exact object key. The device drives a native S3 multipart upload with the standard AWS S3 SDK, configured from `region` plus the access key / secret / session token; the SDK derives the endpoint from the region. 
    pub fn new(scheme: Scheme, access_key_id: String, secret_access_key: String, session_token: String, region: String, expires_at: String) -> S3UploadCredentials {
        S3UploadCredentials {
            scheme,
            access_key_id,
            secret_access_key,
            session_token,
            region,
            expires_at,
        }
    }
}
/// The storage access scheme, which is always `s3` for these credentials.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "s3")]
    S3,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    SchemeUnknown,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::S3
    }
}

