/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// S3UploadCredentials : Short-lived credentials for the broker upload flow to any S3-compatible object store (AWS S3, Cloudflare R2, MinIO, ...). The device drives a native S3 multipart upload with the standard AWS S3 SDK, configured from `endpoint` + `region` plus the access key / secret / session token. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3UploadCredentials {
    /// The storage access scheme, which is always `s3` for these credentials.
    #[serde(rename = "scheme")]
    pub scheme: Scheme,
    /// The STS session access key ID.
    #[serde(rename = "access_key_id")]
    pub access_key_id: String,
    /// The STS session secret access key.
    #[serde(rename = "secret_access_key")]
    pub secret_access_key: String,
    /// The STS session token that must accompany the access key pair.
    #[serde(rename = "session_token")]
    pub session_token: String,
    /// The region used for SigV4 signing. For Cloudflare R2 this is `auto`.
    #[serde(rename = "region")]
    pub region: String,
    /// The S3 API endpoint URL the device points its S3 SDK at. AWS uses a regional endpoint, e.g. `https://s3.us-east-1.amazonaws.com`; Cloudflare R2 uses `https://<account_id>.r2.cloudflarestorage.com` with `region: auto`. 
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// Timestamp after which the session credentials are no longer valid.
    #[serde(rename = "expires_at")]
    pub expires_at: String,
}

impl S3UploadCredentials {
    /// Short-lived credentials for the broker upload flow to any S3-compatible object store (AWS S3, Cloudflare R2, MinIO, ...). The device drives a native S3 multipart upload with the standard AWS S3 SDK, configured from `endpoint` + `region` plus the access key / secret / session token. 
    pub fn new(scheme: Scheme, access_key_id: String, secret_access_key: String, session_token: String, region: String, endpoint: String, expires_at: String) -> S3UploadCredentials {
        S3UploadCredentials {
            scheme,
            access_key_id,
            secret_access_key,
            session_token,
            region,
            endpoint,
            expires_at,
        }
    }
}
/// The storage access scheme, which is always `s3` for these credentials.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "s3")]
    S3,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    SchemeUnknown,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::S3
    }
}

