/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadRuleDestination {
    /// ID of the bucket this rule uploads to.
    #[serde(rename = "bucket_id")]
    pub bucket_id: String,
    /// Name of the bucket this rule uploads to.
    #[serde(rename = "bucket_name")]
    pub bucket_name: String,
    /// The object-path template the collected file is written to. MUST contain `{device_id}` so each device's uploads are namespaced under its own verified ID.
    #[serde(rename = "path")]
    pub path: String,
    /// When the device deletes the local source file after collecting it.
    #[serde(rename = "delete_policy")]
    pub delete_policy: models::UploadDeletePolicy,
}

impl UploadRuleDestination {
    pub fn new(bucket_id: String, bucket_name: String, path: String, delete_policy: models::UploadDeletePolicy) -> UploadRuleDestination {
        UploadRuleDestination {
            bucket_id,
            bucket_name,
            path,
            delete_policy,
        }
    }
}

