/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadDestination : Destination-side details of where an upload was written.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadDestination {
    /// ID of the registered bucket the file was uploaded to.
    #[serde(rename = "bucket_id")]
    pub bucket_id: String,
    /// The object path the file was written to in the destination bucket. Carries the device's verified ID.
    #[serde(rename = "object_key")]
    pub object_key: String,
}

impl UploadDestination {
    /// Destination-side details of where an upload was written.
    pub fn new(bucket_id: String, object_key: String) -> UploadDestination {
        UploadDestination {
            bucket_id,
            object_key,
        }
    }
}

