/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadStatus : The lifecycle status of an upload in the ledger. - `pending`: a presigned URL has been minted but the device has not yet confirmed a durable write. - `uploaded`: the device confirmed a durable write to the bucket. 
/// The lifecycle status of an upload in the ledger. - `pending`: a presigned URL has been minted but the device has not yet confirmed a durable write. - `uploaded`: the device confirmed a durable write to the bucket. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UploadStatus {
    #[serde(rename = "pending")]
    UPLOAD_STATUS_PENDING,
    #[serde(rename = "uploaded")]
    UPLOAD_STATUS_UPLOADED,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    UploadStatusUnknown,
}

impl std::fmt::Display for UploadStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UPLOAD_STATUS_PENDING => write!(f, "pending"),
            Self::UPLOAD_STATUS_UPLOADED => write!(f, "uploaded"),
            Self::UploadStatusUnknown => write!(f, "unknown"),
        }
    }
}

impl Default for UploadStatus {
    fn default() -> UploadStatus {
        Self::UPLOAD_STATUS_PENDING
    }
}

