/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadDeletePolicy : When the device deletes the local source file after collecting it for upload. - `never`: never delete the local file. - `after_upload`: delete the local file immediately once the upload is durably confirmed. 
/// When the device deletes the local source file after collecting it for upload. - `never`: never delete the local file. - `after_upload`: delete the local file immediately once the upload is durably confirmed. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UploadDeletePolicy {
    #[serde(rename = "never")]
    UPLOAD_DELETE_POLICY_NEVER,
    #[serde(rename = "after_upload")]
    UPLOAD_DELETE_POLICY_AFTER_UPLOAD,

    /// Catch-all for values added by the API after this client was
    /// generated. `#[serde(other)]` makes unrecognized strings
    /// deserialize here instead of failing the whole payload.
    #[serde(other)]
    UploadDeletePolicyUnknown,
}

impl std::fmt::Display for UploadDeletePolicy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UPLOAD_DELETE_POLICY_NEVER => write!(f, "never"),
            Self::UPLOAD_DELETE_POLICY_AFTER_UPLOAD => write!(f, "after_upload"),
            Self::UploadDeletePolicyUnknown => write!(f, "unknown"),
        }
    }
}

impl Default for UploadDeletePolicy {
    fn default() -> UploadDeletePolicy {
        Self::UPLOAD_DELETE_POLICY_NEVER
    }
}

