/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadRuleSource {
    /// An absolute glob pattern (must start with `/`) that selects the files to upload.
    #[serde(rename = "glob")]
    pub glob: String,
    /// How often, in seconds, the agent checks matching files for upload eligibility.
    #[serde(rename = "poll_interval_secs")]
    pub poll_interval_secs: i32,
    /// How long, in seconds, a matching file's size and modification time must stay unchanged (quiescent) before it is considered finished and eligible for upload. Files in a format with a finalization marker (e.g. MCAP, parquet) are detected directly; this window is the fallback for other files.
    #[serde(rename = "stability_window_secs")]
    pub stability_window_secs: i32,
}

impl UploadRuleSource {
    pub fn new(glob: String, poll_interval_secs: i32, stability_window_secs: i32) -> UploadRuleSource {
        UploadRuleSource {
            glob,
            poll_interval_secs,
            stability_window_secs,
        }
    }
}

