/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadWithCredentials : Response to a broker upload request. The backend verified the calling device, created the upload ledger entry, authorized the exact `object_key` and provenance, performed digest dedup, and vended short-lived downscoped cloud credentials bound to that one object key. The device uploads directly via the native cloud SDK, then calls `POST /uploads/{upload_id}/confirm`. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadWithCredentials {
    #[serde(rename = "upload")]
    pub upload: Box<models::Upload>,
    #[serde(rename = "credentials")]
    pub credentials: Box<models::UploadCredentials>,
}

impl UploadWithCredentials {
    /// Response to a broker upload request. The backend verified the calling device, created the upload ledger entry, authorized the exact `object_key` and provenance, performed digest dedup, and vended short-lived downscoped cloud credentials bound to that one object key. The device uploads directly via the native cloud SDK, then calls `POST /uploads/{upload_id}/confirm`. 
    pub fn new(upload: models::Upload, credentials: models::UploadCredentials) -> UploadWithCredentials {
        UploadWithCredentials {
            upload: Box::new(upload),
            credentials: Box::new(credentials),
        }
    }
}

