/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadRequiredHeaders : Provenance metadata the device MUST send as headers on the presigned PUT. These values are echoed into the bucket object's metadata and are populated server-side from the authenticated device's identity; the device never supplies them as request input. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadRequiredHeaders {
    /// The verified ID of the device that produced the upload.
    #[serde(rename = "device_id")]
    pub device_id: String,
    /// The ID of the release the device was on when the file was captured.
    #[serde(rename = "release_id")]
    pub release_id: String,
    /// The ID of the deployment the device was on when the file was captured.
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,
    /// The config version active on the device when the file was captured.
    #[serde(rename = "config_version")]
    pub config_version: String,
    /// The digest of the file being uploaded.
    #[serde(rename = "digest")]
    pub digest: String,
    /// The file's last-modified time (mtime) on the device, i.e. roughly when writing finished.
    #[serde(rename = "file_modified_at")]
    pub file_modified_at: String,
}

impl UploadRequiredHeaders {
    /// Provenance metadata the device MUST send as headers on the presigned PUT. These values are echoed into the bucket object's metadata and are populated server-side from the authenticated device's identity; the device never supplies them as request input. 
    pub fn new(device_id: String, release_id: String, deployment_id: String, config_version: String, digest: String, file_modified_at: String) -> UploadRequiredHeaders {
        UploadRequiredHeaders {
            device_id,
            release_id,
            deployment_id,
            config_version,
            digest,
            file_modified_at,
        }
    }
}

