/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadSource : Source-side details of the file on the device that produced an upload.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadSource {
    /// Absolute path of the file on the device. Its basename renders the `{filename}` token in the destination path template.
    #[serde(rename = "file_path")]
    pub file_path: String,
    /// The file's last-modified time (mtime) on the device, i.e. roughly when writing finished.
    #[serde(rename = "file_modified_at")]
    pub file_modified_at: String,
}

impl UploadSource {
    /// Source-side details of the file on the device that produced an upload.
    pub fn new(file_path: String, file_modified_at: String) -> UploadSource {
        UploadSource {
            file_path,
            file_modified_at,
        }
    }
}

