/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadSource : Source-side details of the file on the device that produced an upload.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadSource {
    /// Absolute path of the file on the device. Its basename renders the `{file_name}` token in the upload path template.
    #[serde(rename = "file_path")]
    pub file_path: String,
    /// The file's last-modified time (mtime) on the device, i.e. roughly when writing finished.
    #[serde(rename = "mtime")]
    pub mtime: String,
    /// Timestamp of when the device agent first observed the file on the device.
    #[serde(rename = "first_observed_at")]
    pub first_observed_at: String,
    /// Timestamp of when the device agent most recently observed the file before the upload was minted.
    #[serde(rename = "last_observed_at")]
    pub last_observed_at: String,
}

impl UploadSource {
    /// Source-side details of the file on the device that produced an upload.
    pub fn new(file_path: String, mtime: String, first_observed_at: String, last_observed_at: String) -> UploadSource {
        UploadSource {
            file_path,
            mtime,
            first_observed_at,
            last_observed_at,
        }
    }
}

