/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadRuleSource {
    /// An absolute glob pattern (must start with `/`) that selects the files to upload.
    #[serde(rename = "glob")]
    pub glob: String,
    /// How often the agent checks matching files for upload eligibility, as a duration (e.g. `60s`).
    #[serde(rename = "poll_interval")]
    pub poll_interval: String,
    /// How long a matching file's size and modification time must stay unchanged (quiescent) before it is considered finished and eligible for upload, as a duration (e.g. `60s`). Files in a format with a finalization marker (e.g. MCAP, parquet) are detected directly; this window is the fallback for other files.
    #[serde(rename = "stability_window")]
    pub stability_window: String,
}

impl UploadRuleSource {
    pub fn new(glob: String, poll_interval: String, stability_window: String) -> UploadRuleSource {
        UploadRuleSource {
            glob,
            poll_interval,
            stability_window,
        }
    }
}

