/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadCredentials : Response to a broker upload request. The backend verified the calling device, created the upload ledger entry, authorized the exact `object_key` and provenance, performed digest dedup, and vended short-lived downscoped cloud credentials bound to that one object key. The device uploads directly via the native cloud SDK, then calls `POST /uploads/{upload_id}/confirm`. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadCredentials {
    /// The storage access scheme. Mirrors the `credentials.scheme` discriminator so the device can select its SDK before parsing `credentials`.
    #[serde(rename = "scheme")]
    pub scheme: Scheme,
    /// The vended S3 downscoped credentials.
    #[serde(rename = "s3_credentials", deserialize_with = "Option::deserialize")]
    pub s3_credentials: Option<Box<models::S3UploadCredentials>>,
    /// The vended GCS downscoped credentials.
    #[serde(rename = "gcs_credentials", deserialize_with = "Option::deserialize")]
    pub gcs_credentials: Option<Box<models::GcsUploadCredentials>>,
    /// Timestamp after which the vended credentials expire. On mid-upload expiry the device re-requests exact-key credentials and resumes.
    #[serde(rename = "expires_at")]
    pub expires_at: String,
}

impl UploadCredentials {
    /// Response to a broker upload request. The backend verified the calling device, created the upload ledger entry, authorized the exact `object_key` and provenance, performed digest dedup, and vended short-lived downscoped cloud credentials bound to that one object key. The device uploads directly via the native cloud SDK, then calls `POST /uploads/{upload_id}/confirm`. 
    pub fn new(scheme: Scheme, s3_credentials: Option<models::S3UploadCredentials>, gcs_credentials: Option<models::GcsUploadCredentials>, expires_at: String) -> UploadCredentials {
        UploadCredentials {
            scheme,
            s3_credentials: if let Some(x) = s3_credentials {Some(Box::new(x))} else {None},
            gcs_credentials: if let Some(x) = gcs_credentials {Some(Box::new(x))} else {None},
            expires_at,
        }
    }
}
/// The storage access scheme. Mirrors the `credentials.scheme` discriminator so the device can select its SDK before parsing `credentials`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "s3")]
    S3,
    #[serde(rename = "gcs")]
    Gcs,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    SchemeUnknown,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::S3
    }
}

