/*
 * Miru Agent API
 *
 * The API between the Miru Backend and the Agent; for internal use only
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Upload {
    /// The object type, which is always `upload`.
    #[serde(rename = "object")]
    pub object: Object,
    /// ID of the upload.
    #[serde(rename = "id")]
    pub id: String,
    /// ID of the device that produced the upload.
    #[serde(rename = "device_id")]
    pub device_id: String,
    /// ID of the file rule that produced the upload.
    #[serde(rename = "file_rule_id")]
    pub file_rule_id: String,
    /// The name of the upload collection the producing file rule uploads to.
    #[serde(rename = "upload_collection_name")]
    pub upload_collection_name: String,
    /// Source-side details of the file on the device that produced this upload.
    #[serde(rename = "source")]
    pub source: Box<models::UploadSource>,
    /// Destination-side details of where the file was uploaded.
    #[serde(rename = "destination")]
    pub destination: Box<models::UploadDestination>,
    /// The digest of the uploaded file.
    #[serde(rename = "digest")]
    pub digest: String,
    /// The size of the uploaded file in bytes.
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "status")]
    pub status: models::UploadStatus,
    /// Whether the file was incomplete when collected (the mint request carried `incomplete: true`). Independent of `status`.
    #[serde(rename = "incomplete")]
    pub incomplete: bool,
    /// ID of the release the device was on when the upload was produced.
    #[serde(rename = "release_id")]
    pub release_id: String,
    /// ID of the deployment that was active on the device when the upload was produced.
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,
    /// Timestamp of when the upload was durably confirmed. Null until the upload completes.
    #[serde(rename = "uploaded_at", deserialize_with = "Option::deserialize")]
    pub uploaded_at: Option<String>,
    /// Timestamp of when the upload was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the upload was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// ID of the workspace that owns the upload.
    #[serde(rename = "workspace_id")]
    pub workspace_id: String,
}

impl Upload {
    pub fn new(object: Object, id: String, device_id: String, file_rule_id: String, upload_collection_name: String, source: models::UploadSource, destination: models::UploadDestination, digest: String, size: i64, status: models::UploadStatus, incomplete: bool, release_id: String, deployment_id: String, uploaded_at: Option<String>, created_at: String, updated_at: String, workspace_id: String) -> Upload {
        Upload {
            object,
            id,
            device_id,
            file_rule_id,
            upload_collection_name,
            source: Box::new(source),
            destination: Box::new(destination),
            digest,
            size,
            status,
            incomplete,
            release_id,
            deployment_id,
            uploaded_at,
            created_at,
            updated_at,
            workspace_id,
        }
    }
}
/// The object type, which is always `upload`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "upload")]
    Upload,
    /// Catch-all for values added by the API after this client was generated.
    #[serde(other)]
    ObjectUnknown,
}

impl Default for Object {
    fn default() -> Object {
        Self::Upload
    }
}

